### ISSUE TITLE
Errors installing node

### ISSUE THREAD

**Issue by PascalTemel** [skycocker/chromebrew#155]
Whenever I try installing node I get the following error:

```
/usr/local/bin/crew:32:in `const_get': uninitialized constant Node (NameError)
        from /usr/local/bin/crew:32:in `setPkg'
        from /usr/local/bin/crew:49:in `block in search'
        from /usr/local/lib/ruby/2.0.0/find.rb:43:in `block in find'
        from /usr/local/lib/ruby/2.0.0/find.rb:42:in `catch'
        from /usr/local/lib/ruby/2.0.0/find.rb:42:in `find'
        from /usr/local/bin/crew:48:in `search'
        from /usr/local/bin/crew:349:in `<main>'
```

This does not happen when I try installing other tools like htop.

**Comment by RyanNHG** [comment]
This is an issue in the node.rb file.

The class name is 'Nodejs' instead of 'Node'.

I made my revision over [here](https://github.com/RyanNHG/chromebrew/commit/b0c6ff99e848822d75a33f16d201b0a3982688ce).

Hopefully, @skycocker can merge this change into master.

**Comment by Bifros7** [comment]
@RyanNHG I tried your patch but now it doesn't recognize the package "Node" at all. Maybe I'm doing something wrong, I don't know. I'm trying to install node_stable now, I hope it will compile fine.

**Comment by Bifros7** [comment]
I was able to fix the 'cannot find ld' error by manually setting the configure parameter --without-snapshot

**Comment by RyanNHG** [comment]
@Bifros7, that's great news. 

I'll try the "--without-snapshot" parameter today. 

I had the same issue with ld and couldn't find the right parameter to fix it.

**Comment by faddah** [comment]
+1 in seeing this also - it would be nice to incorporate @RyanNHG fix as pull request on this one. @skycocker - are you seeing this, please? really hard to get the node to install.

best,

‒  faddah
    portland, oregon, u.s.a.

**Comment by faddah** [comment]
ok, further on the above for @skycocker -- i tried doing ```crew update```, and it said it had a included a pull request @RyanNHG , so i assume that was for the node install.  i then ran ‒

```$ crew install node --without-snapshot```

when i do this, it goes almost all the way through the install, it does the ```./configure``` then the ```make```, but as it starts the ```sudo make install```, i get this, similar to what others have seen over at the bug for the node_stable, #143 . ‒

```

...
  g++ -pthread -rdynamic -m64 -fuse-ld=gold -B/usr/local/tmp/crew/node-v4.3.0/third_party/binutils/Linux_x64/Release/bin -m64  -o /usr/local/tmp/crew/node-v4.3.0/out/Release/mksnapshot -Wl,--start-group /usr/local/tmp/crew/node-v4.3.0/out/Release/obj.target/mksnapshot/deps/v8/src/snapshot/mksnapshot.o /usr/local/tmp/crew/node-v4.3.0/out/Release/obj.target/deps/v8/tools/gyp/libv8_base.a /usr/local/tmp/crew/node-v4.3.0/out/Release/obj.target/deps/v8/tools/gyp/libv8_nosnapshot.a /usr/local/tmp/crew/node-v4.3.0/out/Release/obj.target/deps/v8/tools/gyp/libv8_libplatform.a /usr/local/tmp/crew/node-v4.3.0/out/Release/obj.target/deps/v8/tools/gyp/libv8_libbase.a -Wl,--end-group -ldl -lrt
collect2: fatal error: cannot find 'ld'
compilation terminated.
make[1]: *** [/usr/local/tmp/crew/node-v4.3.0/out/Release/mksnapshot] Error 1
make[1]: Leaving directory `/usr/local/tmp/crew/node-v4.3.0/out'
make: *** [node] Error 2
node failed to install: `make` exited with 2

```

and it fails there, after 45 minutes to an hour of compiling, every time.

any hope for a fix on this and the node_stable install? both fail in this way.

best,

‒  faddah
    portland, oregon, u.s.a.

**Comment by Bifros7** [comment]
@faddah you seem to be having the same issue I had:  `collect2: fatal error: cannot find 'ld'`

I set the --without-snapshot parameter inside the node.rb file, I'm not sure if you can add parameters when running the crew command.

**Comment by skycocker** [comment]
@faddah why would it run as sudo? do you run crew with sudo?

**Comment by faddah** [comment]
@Bifros7 & @skycocker -- sorry, just seeing your comments now.

@skycocker - i don't believe i said i ran any command from ```crew``` with ```sudo```, anywhere. where are you seeing that? i don't believe i did that, at all. but this is over a week since i looked at this, so i could be wrong.

@Bifros7 - i am trying again right now with ```crew install node_stable``` and seeing if it works. i will let you both know. if not, i'll try the ```--without-snapshot``` flag in the ```node.rb``` ruby gem install file, and see if that works. but if that's what fixes it, it should really be a pull request.

i'll let you both know.

best,

--  faddah
    portland, oregon, u.s.a.

**Comment by faddah** [comment]
@Bifros7 & @skycocker -

ok, i just did ```crew update``` yet again then ran ```crew install node``` to get node.js v4.3.0 on my chromebook. it came back and gave the exact same error i listed above.

so i did what @Bifros7 suggested and found the crew ```node.rb``` file and edited so after ```./configure``` i had the ```--without-snapshot``` flag. still didn't work, same error after ~45 minutes of compiling.

@Bifros7 - am i putting the ```--without-snapshot``` flag in the right place?
@skycocker - again, i'm not using ```sudo``` with anything here.
any help in getting this fixed would be appreciated.

best,

--  faddah
    portland, oregon, u.s.a.

**Comment by Bifros7** [comment]
@faddah What I did was edit the line `system "CC='gcc' python2.7 ./configure"` to `system "CC='gcc' python2.7 ./configure --without-snapshot"`. It sounds like you did exactly that. Are you sure you edited the right package (node or node_stable)? Also, after running crew update, this file resets to the default and reverts your changes, so make sure you change the file AFTER updating.

**Comment by faddah** [comment]
@Bifros7 - it was the node.rb for node, not node_stable, because it was pulling down the version i wanted, node.js v4.3.0. yes, i edited that line just the same way. still get that error in compile.

btw, exact same thing happens with the node_stable install. i'll willing provide any system info necessary on my acer chromebook if it'll help fix this. please advise.

best,

--  faddah
    portland, oregon, u.s.a.

**Comment by Bifros7** [comment]
@faddah Can you tell me the path to the file you're editing? If I remember correctly, crew installs the packages to another folder, so you shouldn't be editing the file in the cloned git folder because that won't make a difference. I don't quite remember where the file you need to edit is located (or if this is even the true), maybe you can search for it with `find`? Sorry I can't help you more, my Chromebook is running linux natively right now and I completely ditched ChromeOS.

**Comment by faddah** [comment]
@Bifros7 ‒

/usr/local/lib/crew/packages/node.rb
/usr/local/lib/crew/packages/node_stable.rb

that's where they be. there are several other node.rb's all over my system, none related to crew, though.

and my python is python v2.7.10.

best,

‒  faddah
    portland, oregon, u.s.a.

**Comment by faddah** [comment]
hi @Bifros7 & @skycocker ,

ok, so i got node_stable, v5.3.0, installed by adding the ```--without-snapshot``` to the node_stable.rb file. that worked, then i updated npm to the latest (npm v3.8.6) and installed the npm ```n``` package that is a node.js version manager, updated to the latest (v5.10.1), and also added the LTS version (v4.4.3). so it's ok for now. one you have node, easy enough to add npm packages and upgrade/downgrade to what you need.

but @skycocker ‒ something really needs to be done with these packages, both ```node``` and ```node_stable```, so they work out of the box, please. the node.rb still does not work, even with the ```--without-snapshot``` flag.

hope this helps toward a solution.

best,

‒ faddah
  portland, oregon, u.s.a.

**Comment by Bifros7** [comment]
@faddah Glad you got it working.

**Comment by thedamian** [comment]
Fixed in pull https://github.com/skycocker/chromebrew/pull/173

**Comment by lyxell** [comment]
Closing as resolved, please reopen if I'm incorrect.

**Comment by meekmachine** [comment]
It looks like iun the latest version someone has replaced the install script for node with something "fake" in order to add a dependency called nodebrew. I switched to the version of node.rb from an older branch and it works fine.  Why was the install file switched?

**Comment by uberhacker** [comment]
@meekmachine: We replaced the node package since nodebrew can install binaries and rather than manage the binaries ourselves, we decided to let nodebrew handle it.  You can install any node version simply by executing the following: `nodebrew install-binary <version>`.  For more info, see https://github.com/skycocker/chromebrew/issues/1633.
