### ISSUE TITLE
Old packages 

### ISSUE THREAD

**Issue by Brunux** [skycocker/chromebrew#175]
Hi everybody  just a question I can see that there are some old package is there a reason to maintain all those old packages, like those can't be updated because local dependencies in chromeos or it is just happen that hasn't been updated?

**Comment by thedamian** [comment]
Is there any packages that aren't working? If they're failing you can do a pull request to fix that.

**Comment by Brunux** [comment]
Hi @thedamian is not that so far package are working just fine, but I was wondering if there is a reason to have old package, maybe some dependencies in chromeOS or it is just that hasn't been updated?

**Comment by thedamian** [comment]
@Brunux you've created a new issue. If there is something to fix please specify what you think should be fixed. Or better yet submit a fix. If you thought you were just opening a thread for conversation, this is the wrong place for that.

**Comment by Brunux** [comment]
I thought there was a question tag for issues here, sorry my mistake.

**Comment by thedamian** [comment]
Don't be sorry. I should be. This is the place for discussion. 

Please make a suggestion because your issue is a little too general

**Comment by Brunux** [comment]
Thank you for your kindness @thedamian well basically I'm building nmap package so I was check for  dependencies in the package folder when I realize that the base system, gcc and make for example are kind of old so I was wondering if that happen for a reason like to match the base system of the chromeos or it happens just because those are not been updated lately. Thank you!

**Comment by thedamian** [comment]
@Brunux I had this problem before. Ruby is an example of this (personally git being the older version was an issue for me  too for version of dotnet that I was working on) 

I "hacked" this (and skycoker wasn't too happy, but was kind to me and let it go through) by adding a "ruby_latest" package.

So technically there's a ruby.rb and ruby_latest.rb file to fix this. (this is different than node and node_current because those are two different products technically) but the ruby_latest just updates ruby without touching the main package that I believe is needed.

It's a BAD fix. the correct one would be to update the initial packages first downloaded by the install.sh but no one has had the time to update those. And because of dependencies we've "lived" with just doing bad hacks like I did.

I'd love to see a gcc, git and ruby update throughout the system but haven't had the time.

an update to gcc and make (and for it to be done successfully even if using the "_latest" hack) would be very welcome by me and I'm sure by  the community.

**Comment by Brunux** [comment]
Oh right, that's good to know, for now I'm going to build nmap and maybe we can do a plan to update the base system later on, thanks.

**Comment by lyxell** [comment]
@Brunux Can we close this?

**Comment by Brunux** [comment]
Sure, thanks guys
