### ISSUE TITLE
Update the toolchains

### ISSUE THREAD

**Issue by lyxell** [skycocker/chromebrew#185]
I've cross compiled a gcc-toolchain for ARM and created a repository for it (see https://github.com/lyxell/chromeos-toolchains, thanks @bfayers for all the testing).

While I was at it I also cross compiled the same toolchain for x86_64 and i686.

These toolchains uses musl (https://www.musl-libc.org/) instead of glibc to create encapsulation inside /usr/local. Unlike glibc, musl will not interfere with the native libraries and the native libraries will not interfere with musl, this should solve #49 #56 #103 #131 #142 #171 and similar issues. It should also get rid of this https://github.com/skycocker/chromebrew/search?utf8=%E2%9C%93&q=shortarch

Musl also makes cross compiling possible which means we are able to update the toolchain for all architectures from a single machine in one go.

GCC is bumped to the latest version of the 4.x branch (4.9.3).

If people would like to try it out the tarballs can be found here: https://github.com/lyxell/chromeos-toolchains/blob/master/README.md. I've not included a C++ compiler included yet, so nodejs won't compile, but everything else in Chromebrew should work fine. If you run into an issue you can file it inside that repository so we don't clutter this thread, searching through #168 could also be helpful.

What are your general thoughts on this? Are people on x86_64 and i686 be interested in updating their toolchains as well?

**Comment by minektur** [comment]
I personally would like a self-hosting compiler build.  I'm fine using a boot-strapped something or other from crouton, but we should be able to get to a gcc build with the gcc we install - e.g. start with the cross-compiled one, build a temporary gcc and use that to build a 'real' gcc which should be the same as the temporary one... Or something like that.

**Comment by lyxell** [comment]
@minektur I'm not really sure on what you mean, could you elaborate? Why would there be any advantages of using a self-hosted build? The rest of the OS is cross compiled with the same settings.

**Comment by minektur** [comment]
well.... call me a purist? but... Ok I found someone else who explained it pretty well.  Read this http://programmers.stackexchange.com/questions/263651/why-are-self-hosting-compilers-considered-a-rite-of-passage-for-new-languages    stackoverflow question and find the answer by DefinitelyNotSteve, where he paraphrases steve yegge.

Here is my summary of his summary and thoughts, well point 3 anyway.  It is an excellent way to make sure it actually works.  Building a compiler is a complicated task.  If the compiler can build itself and get a copy of itself out then you know its working, right?  

Quoting from the 'linux from scratch' build manual:

make bootstrap
The 'bootstrap' target does not just compile GCC, but compiles it several times. It uses the programs compiled in a first round to compile itself a second time, and then again a third time. It then compares these second and third compiles to make sure it can reproduce itself flawlessly. This also implies that it was compiled correctly.

That use of the 'bootstrap' target is motivated by the fact that the compiler one uses to build the target system's toolchain may not have the very same version of the target compiler. Proceeding in that way one is sure to obtain, in the target system, a compiler that can compile itself.


All that said - we're not rebuilding the whole system, just auxiliary tools, and so we probably can get away with just using something that works, rather than something that is kind of provably correct.

**Comment by lyxell** [comment]
@minektur Well, I guess it is good to do some testing to make sure it is working, but if it is, there's actually no sane reason at all to use a bootstrapped compiler instead of a cross compiled one and I can't think of an operating system in the world which are doing this.

**Comment by bfayers** [comment]
@lyxell Hey, I never did get python to compile don't really know why it was having issues with dependencies even though they where compiled and installed. even tried linking them.

**Comment by lyxell** [comment]
@bfayers Alright, I'll look into it.

**Comment by bfayers** [comment]
@lyxell Did you get any further? Fine if you didnt I've tried a few times to build with 0 succcess so far.

**Comment by bfayers** [comment]
@lyxell, there is a bit of an issue with the toolchain (for arm) I decided to reinstall chromeos and the toolchain is 299M and the root partition (/) only has 288M avaliable, so the only way is to put it in a folder and use PATH and EXPORT, any solution? might it be that im on chrome stable?

**Comment by lyxell** [comment]
@bfayers That sounds strange, shouldn't the Samsung Chromebook have like 16GB storage? The reserved space should be the same on the beta and stable channels.

**Comment by bfayers** [comment]
@lyxell Its always been like that,  small amount in / its /home/chronos/user that has about 8gb

**Comment by lyxell** [comment]
@bfayers I'll look into it when I'm back from vacation. I think I've managed to get Python working as well.

**Comment by bfayers** [comment]
@lyxell okay, cool. Just looks like finding a location withing /home (which has 8.2GB) and using /etc/environment to set it all.

**Comment by jam7** [comment]
I was trying to use this musl-gcc for a while on ARM.  However, I was having some difficulties to compile programs which use /usr/lib libraries.  For example, /usr/local/lib/libssh2 uses /usr/lib/libssl.so and /usr/lib/libcrypt.so so that glibc-styled libc too.  However, musl-gcc requires to link with musl libc and causes link errors.

It is possible to create libssl.so in /usr/local/lib for ARM.  However, it is difficult doing that on only ARM because of dependencies (e.g. ARM libssh2 requires openssl, but X86 and X86_64 don't).

Jumping to musl-gcc on all architectures may solve this problem but requires a lot work.

BTW, @lyxell  thank you for providing dockerfiles.  I learned a lot.

**Comment by lyxell** [comment]
@jam7 Yeah, you're right. I did it that way on purpose, to resolve conflicts between the shared libraries. While I think it would be the optimal way to do it, I agree that it would be a lot of work and might introduce new bugs. The biggest problem would be c++-support as well. I have had a hard time finding good references for cross compiling musl with libstdc++.

No problem, I'm glad it was helpful.

**Comment by lyxell** [comment]
Closing in favor of #235

**Comment by JL2210** [comment]
@lyxell Sorry if I'm bothering you, but I'm really thinking about creating a fork/branch of Chromebrew for Musl, just like your idea. If you could help in any way, or maybe bring back your repository, please do.
