### ISSUE TITLE
How to test package file?

### ISSUE THREAD

**Issue by hsharrison** [skycocker/chromebrew#187]
The homepage describes how to create a rb file for a new package but not how to use a local rb file. How do I actually run it? Do I have to uninstall the canonical chromebrew then reinstall my own copy, or is there an easier way?

**Comment by lyxell** [comment]
Move the file to `/usr/local/lib/crew/packages`, e.g. `/usr/local/lib/crew/packages/mypackage.rb`, then run `crew install mypackage`.

This should probably be added to the README.md.

**Comment by hsharrison** [comment]
Excellent, thanks for the info.

**Comment by minektur** [comment]
If anyone can explain how the file registration works - how chromebrew picks up what files got installed - I'd love to hear - it should be part of any "here is how to make a package" instructions.  I got it to work by mindlessly coping what another package did, but I don't have a deep enough understanding to know why it works...

**Comment by lyxell** [comment]
@minektur When a package is installed all files are first moved to `/usr/local/tmp/crew/dest`, then, using the `file` command, a file containing all the resulting filenames are saved into `/usr/local/etc/crew/meta/`. Most of it happens here: https://github.com/skycocker/chromebrew/blob/8eef57d094e11e9235ba424ee1e9f66ac88c34d1/crew#L245-L286

**Comment by hsharrison** [comment]
@minektur The packages get compiled, so it's up to the package what files are included. crew simply downloads the file in the source_url field, checks it hash against the source_sha1 field, then runs the commands under `self.build`.

**Comment by lyxell** [comment]
@hsharrison Can we close this issue?

**Comment by hsharrison** [comment]
Fine with me. Only reason I didn't already is that you mentioned changing the README.

**Comment by minektur** [comment]
what I mean is not source_url/sha1 hash (incidentally, we should switch to a stronger hash some time), but how the list of files that got installed is automagically recorded so you can crew remove them later -  /usr/local/etc/crew/meta/foo.directorylist and foo.flielist  for package foo.

I copied what another package did, and it seemed to do the right thing, but when I did slightly different ruby code, it didn't work and I didn't see why.  Somehow in a recipe, in the install function, you can make it so that files you install get recorded for later uninstallation, but how that happens is beyond my ruby-reading skills.  

All that said, Sure we can close this bug, I'm just jabbering.

**Comment by lyxell** [comment]
@minektur Read my comment again. All the files are first installed into `/usr/local/tmp/crew/dest` which is an empty directory, that way, it is possible to record the filenames of all installed files for later use.

**Comment by lyxell** [comment]
@hsharrison I added the required steps to the wiki https://github.com/skycocker/chromebrew/wiki/Creating-a-package
