### ISSUE TITLE
libpng install cannot download, checksum mismatch

### ISSUE THREAD

**Issue by faddah** [skycocker/chromebrew#199]
i've tried to install libpng with `crew install libpng` on my acer chromebook C720P-2600.

when i do, it can't even finish after the download, due to a checksum mismatch ‒

```

crew install libpng
Found libpng, version 1.6.19
Found libpng, version 1.6.19
No precompiled binary available for your platform, downloading source...
--2016-07-15 13:30:33--  http://downloads.sourceforge.net/project/libpng/libpng16/1.6.19/libpng-1.6.19.tar.xz
Resolving downloads.sourceforge.net... 216.34.181.59
Connecting to downloads.sourceforge.net|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-07-15 13:30:34 ERROR 404: Not Found.

Checksum mismatch :/ try again

```

so i think this needs to be pointed at a correct download with a corrected checksum.

best,

—  faddah
     portland, oregon, u.s.a.

**Comment by thedamian** [comment]
type to be a contributor @faddah 
the issue is either the sha1 calculation or the actual file is missing. 

you can see the words "404 not found" not "checksum mismatch" that you see below the real error.

So you have to find out why. 

p.s. I can tell if it's because they changed to a new version an ddon't keep the old versions in the same place. so the new file is:

http://downloads.sourceforge.net/project/libpng/libpng16/1.6.24/libpng-1.6.24.tar.xz
and the sha1 signature is: b8fa86449bebd7b1cda71e0ed2cd417b6596ce78

(you can get the sha1 signature by doing "sha1sum" in linux and chromebooks or "openssl sha1 {filename.rb} " on most other places. In windows there's an app that will add it to you "right click and choose properties" option.
