### ISSUE TITLE
[rust]  error reading rustc version on i686

### ISSUE THREAD

**Issue by lovedheart** [skycocker/chromebrew#2135]
Running 
"rustup install stable"
gives
stable-i686-unknown-linux-gnu installed - (error reading rustc version) 

Running
"rustup update"
outputs
info: syncing channel updates for 'stable-i686-unknown-linux-gnu'
error: rustup is not installed at '/home/chronos/user/.cargo'

**Comment by lovedheart** [comment]
> sudo rustup install stable

error: could not create home directory: '/root/.rustup'
info: caused by: Read-only file system (os error 30)

**Comment by uberhacker** [comment]
@lovedheart: Thank you for reporting this issue.  I noticed some trouble with rustup also.  One thing you should NEVER do is prefix commands with sudo.  Not only do you have problems with read-only errors, it can do some other destructive things in `/usr/local` that can completely hose your Chromebrew install.  My guess is the problem is because the `/home/chronos/user` directory is not executable.  The workaround might be to symlink to the `/usr/local` directory where the rust files are stored.
