### ISSUE TITLE
How are you doing this? Can it scale?

### ISSUE THREAD

**Issue by plunkinguitar** [skycocker/chromebrew#214]
A friend of mine and I are doing something similar and are wondering how you are doing this, would it be possible to develop something like a real package manager to work with the ubuntu repository? Also, how do you manage dependencies and the different file structure that chromeos(gentoo based) has as opposed to the file structure of ubuntu(debian based)?

**Comment by PoisonNinja** [comment]
Hi @plunkinguitar, strange to see you here :).

I don't know the exact implementation details, but if it's anything like Homebrew, this should be reasonably correct.

1. Chromebrew downloads the source package from the link specified from the package recipe. You can see them in the packages directory.
2. Chromebrew then extracts the packages and verifies the checksums
3. It then builds the package as specified in the self.build part of the recipe
4. Finally Chromebrew installs the package following the instructions in the self.install part of the recipe.

An alternative is that Chromebrew can download and install prebuilt binaries, although those are more rare. 

You can see the details of a package at <https://github.com/skycocker/chromebrew/wiki/Creating-a-package>.

Answering your question about how does it manage the file system differences: The filesystems of Gentoo and Ubuntu are very similar, and the folders that do matter (/usr/* and /usr/local/*) are present on both.

Did you know that you can actually install apt-get and dpkg on Chrome OS? It's quite a hack, but it works. I had a repository, but I deleted it. I can share you a document where I documented my steps to get apt-get working.

**Comment by smerkousdavid** [comment]
Hey Jason, I didn't expect you to be on this thread. We have also got dpkg and apt-get working on the chrome-side but it's really hacky and fails about %30 of the time because of the wrong configs. Also since so many depend on the non modified (by gentoo) libc library that we receive segmentation faults constantly. I am still trying to figure out how to fix it without completely ruining chrome os because it has happened multiple times already. Oops

**Comment by PoisonNinja** [comment]
Yeah, another problem was I kept on running out of space. I hacked around that by binding a folder on the bigger partition over /usr/local, but it's disgusting. On a side note, do you get seg faults with Chromebrew if you run ldconfig?

**Comment by smerkousdavid** [comment]
@PoisonNinja Yeah I had the same problems that usr/local would run out of space and to expand it we would have to rootmount which means a double reboot and a pain since if they cancel the remount which is not fun on lower level folder (@plunkinguitar has tried) can screw up chromeos and it takes multiple shots. Also I don't think I remember getting seg faults with ldconfig. I haven't used chromebrew for a while. We have been using the google packages instead since it's been a lot smaller and working more efficiently.

**Comment by PoisonNinja** [comment]
@smerkousdavid https://github.com/PoisonNinja/uoc is the repo with my attempt at getting dpkg and apt-get to work on Chrome OS

**Comment by TheLonelyGhost** [comment]
Slightly off-topic from how this current thread is going, but relevant to the original topic:

Has anyone considered how Homebrew, the project this was clearly based off of, has been recently refactored to allow [cross-platform support](https://github.com/Homebrew/brew/pull/168)? Why not reuse the architecture from Homebrew and just focus remaining efforts on supporting packages on ChromeOS?

**Comment by minektur** [comment]
@TheLonelyGhost checkout linuxbrew (a linux port of homebrew) which has rudimentary chromeos support - along with an install doc/script from @DoomHammer called brewstrap  (https://github.com/DoomHammer/brewstrap)  - though it doesn't look like it has been updated in a while.

**Comment by DoomHammer** [comment]
Might not work right know though I am trying to make it work again ;)

**Comment by thedamian** [comment]
brew can be installed by this link

https://github.com/Linuxbrew/brew/wiki/Chromebook-Install-Instructions

can I close this thread since it just seems like a troll thread?

**Comment by minektur** [comment]
Just be prepared to fiddle a bit - @doomhammer on github made a package
'brewstrap' that also helped install - both the instructions and the script
dont work 100% and it CAN be made to mostly work, but I'd consider it a
work-in-progress.

installing the linuxbrew fork of chromebrew on chromeos would be great if
it could be made to work reliably.

**Comment by PoisonNinja** [comment]
@thedamian sure
