### ISSUE TITLE
Python Tk Support

### ISSUE THREAD

**Issue by superloach** [skycocker/chromebrew#2531]
Chromebrew's Python doesn't have Tk support.
I have a feeling this will be useful now that we have GUI 👉👁👅👁👉
```shell
python3 -c "import tkinter"
```
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by ukscone** [comment]
slow working on this and thus built tcl and tk to check what needs doing to package and stumbled across a slight problem running tk graphic progs. if i just run them then no gui, just sit there until i ctrl-c, if i run via sommelier -X --x-display=:0 then it gives me gui (and of course the socket errors) anyone got any idea why i need to use sommelier manually? because they are scripts not binaries?

**Comment by superloach** [comment]
Huh, that is odd...
I would mess around with it myself, but I'm terrible at getting things to build properly 🤣

**Comment by ukscone** [comment]
tcl and tk build beautifully (if something could be said to but my meaning is clean with no errors or warnings and with default configure settings but although it's not a biggy (other than the ugly socket warnings) it is flummuxing me why. sure it's something obvious but can't see it yet

**Comment by JL2210** [comment]
I could try this, but I'm busy. We still have a long way to go to enable Python support in gtk, including removing `--disable-python` in all the gtk3-related packages.

**Comment by JL2210** [comment]
It should be fixed by now. Try `crew install tk`. @uberhacker, could you close this?

**Comment by skiman6010** [comment]
Closing because package was added to crew. Thanks @JL2210!
