### ISSUE TITLE
Broken duplicate of Pkg-config

### ISSUE THREAD

**Issue by lyxell** [skycocker/chromebrew#263]
There's a duplicate Pkg-config package introduced in commit 2338f0a4a2bb1e4a54e8cb470f9ddf124b56a3f1 which is broken.

Pkg-config is not a valid class name in ruby and trying to install the package will throw a syntax error.

**Comment by thedamian** [comment]
WOAH! I didn't mean to merge that in, what the hell happened. I never did a pull request!!!!

Damn it. I don't think any of them can be built because I was having a cascading set of dependancies that I didn't get to the end of. 

CRAP. I've fixed the name lyxell, but I'll have to finish that up. It's all to build DotNet Core.

I think I'll leave it now for now just in case anyone needs it. but I'm worried the work in my repo is getting into the main somehow.

**Comment by lyxell** [comment]
Alright.
