### ISSUE TITLE
Could we get Man-pages?

### ISSUE THREAD

**Issue by iamchanghyunpark** [skycocker/chromebrew#27]
Okay, this may not be a chromebrew specific issue, 
But I was looking for a way to install man pages into crosh...

I checked out the following man-pages, and I've installed the manuals from below
https://www.kernel.org/doc/man-pages/

however, I haven't been able to find the actual man 'reader' binary, or source code...

Any ideas?

**Comment by lyxell** [comment]
@jbaum98 I don't have a chromebook at the moment to test this myself, could you provide what errors you get when trying the recipe you attached?

**Comment by jbaum98** [comment]
Sorry I don't use chromebrew on my chromebook anymore, so I can't test. I wish I'd written down the errors for other people though... sorry.

**Comment by ealgase** [comment]
I'd like this, too.  I need a man reader and don't want to use Crouton.

**Comment by thedamian** [comment]
@ealgase Perfect: Grab the package the amazing @jbaum98 made: https://github.com/jbaum98/chromebrew/commit/f0474699da70ebd2352c1eb2559db37f1b19bb8a

put it in your /usr/local/lib/crew/packages

then run "crew install man_pages"

and tell us the error it gives you (because he says there's an error)

If it tells you to look for a file for the error spit it out.

I'm at work and can't try this.

**Comment by thedamian** [comment]
oops. I did a quick check and it looks like @jbaum98 deleted the file in dropbox.

I can host it for you @jbaum98 give me a link to download it and I'll try it and reupload it somewhere

**Comment by jbaum98** [comment]
I'm sorry but I can't find the binary. It seems weird that I would have deleted it especially because I'm still hosting the JDK8 binary. I just reinstalled Chromebrew though, so I'll take another crack at this formula in the next couple days.
