### ISSUE TITLE
Chrome OS 72 has glibc 2.27

### ISSUE THREAD

**Issue by bsiegert** [skycocker/chromebrew#2890]
## Description

I am on dev channel. The `glibc` package (installed from binary, as part of the default install) contains dangling symlinks to system libs, because Chrome OS itself is now on glibc 2.27. Compiling anything thus fails with

```shell
$ gcc -o foo foo.c
/usr/local/bin/ld: cannot find /usr/local/lib64/libc.so.6
/usr/local/bin/ld: cannot find /usr/local/lib64/ld-linux-x86-64.so.2
collect2: error: ld returned 1 exit status
$ ls -l /usr/local/lib64/libc.so.6
lrwxrwxrwx. 1 chronos chronos 12 Jun 25 02:32 /usr/local/lib64/libc.so.6 -> libc-2.23.so
$ ls -l /usr/local/lib64/libc-2.23.so
lrwxrwxrwx. 1 chronos chronos 19 Jun 25 02:32 /usr/local/lib64/libc-2.23.so -> /lib64/libc-2.23.so
$ ls /lib64/libc-*.so
/lib64/libc-2.27.so
```

Maybe it is in fat time to use glibc 2.27, as suggested in #2885?

## Versions and system information

glibc version 2.23

chromebrew: 1.0.4

ChromeOS: 
```
CHROMEOS_RELEASE_BUILDER_PATH=caroline-release/R72-11264.0.0          
CHROMEOS_RELEASE_BUILD_NUMBER=11264                                   
CHROMEOS_RELEASE_BUILD_TYPE=Official Build                            
CHROMEOS_RELEASE_CHROME_MILESTONE=72                                  
CHROMEOS_RELEASE_DESCRIPTION=11264.0.0 (Official Build) dev-channel caroline
```

Model: Samsung Chromebook Pro

Architecture: `x86_64`

**Comment by uberhacker** [comment]
Thank you for the heads up @bsiegert.  We will cross this bridge once 72 becomes the stable release.

**Comment by JL2210** [comment]
This is great! After we make this update, the cross script can finally be perfected and will work!

**Comment by JL2210** [comment]
I tried this before, back when glibc 2.23 gave segfaults. It didn't work. However, if this is the new system 
C library, it most likely will.

**Comment by sajjaadf** [comment]
can I use your cross script?

**Comment by JL2210** [comment]
@sajjaadf Doesn't work yet. @bsiegert wget https://ftp.gnu.org/gnu/libc/glibc-2.27.tar.xz
NOT SUPPORTED!

**Comment by sajjaadf** [comment]
When it works can I use it?
[image: Picture]
Sajjaad Farzad
About Me
<https://about.me/sajjaadf?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by JL2210** [comment]
@sajjaadf @bsiegert If you intend to do anything with Chromebrew, you need to revert to the stable channel. The stable channel is the **only** supported channel.

**Comment by blu** [comment]
Just a heads-up: r72 has landed on the beta channel, bringing along the same problem.

**Comment by JL2210** [comment]
@uberhacker, it's `glibc`, not `glib`. `glib` stands for GNOME Library.
`glibc` stands for GNU libc.

**Comment by JL2210** [comment]
Sorry about that. I was on my email, and didn't see the edit you made.

**Comment by JL2210** [comment]
@blu Check the `update-glibc-2.23-2.27` branch on @uberhacker's fork of Chromebrew.
How's Wayland development going?

**Comment by blu** [comment]
@JL2210 Thanks, will do! Wayland's on the backburner ATM, hopefully I'll kick back into it full swing in a couple of weeks.

**Comment by nealey** [comment]
Chrome 72 is now stable.

**Comment by blu** [comment]
> Chrome 72 is now stable: I'm on the stable channel and just hit a bunch of dangling symlinks.

This is normal for r72 and current crew. It can be addressed as described here: https://github.com/skycocker/chromebrew/issues/2890#issuecomment-453760111

**Comment by nealey** [comment]
Yes, thank you. I just meant to add to the issue that we have now reached a state where no up-to-date version of ChromeOS will have glibc-2.23, because of [this comment](https://github.com/skycocker/chromebrew/issues/2890#issuecomment-441251523):

> We will cross this bridge once 72 becomes the stable release.

**Comment by nealey** [comment]
This issue appears to have been resolved recently. I can't close the issue but that may be appropriate.

**Comment by adawdev** [comment]
Hello.

I know this is an old topic, but when I come across things that "can't be done" I just can't seem to help myself but to try and do them anyway.

Results;

[version_report.txt](https://github.com/user-attachments/files/27619110/master_crew_dev_hack.txt)

If you're going to ask "why?"...

Being told it can't be done was what urged me to install my first Linux distro in a dual boot setup on my single drive Windows machine with no thumb drive, DVD, or netboot. grub2 is neat... that only took three lines, this was a bit more complex but now I have gcc and can compile portage locally... with EoS coming fast to atlas and being homeless, this machine needs to be self sufficient to keep me going and I won't tolerate out of date build tools just because I have an immutable root fs. It's not good enough to be secure, I want to be secure and independently competitively functional. Why would I want to build on a platform using libraries four+ years old in some cases? Once I have portage built, I can compile a Gentoo kernel that uses the atlas board's configs (unique audio and power management stuff that breaks with generic amd64 images from what I've read) and sign it to boot through the Depthcharge bootloader instead of MrChromebox.

Maybe I'm reinventing the wheel. I don't get online to talk to other people about my projects much. But this seemed like a big enough success to share.

My modified install.sh failed when attempting to install the `crew_profile_base`, around line 617. I did the rest manually.

[hacked_dev_channel_chromebrew_install.sh](https://github.com/user-attachments/files/27619071/hacked_dev_channel_chromebrew_install.sh)

[trimmed_bash_history_dump.txt](https://github.com/user-attachments/files/27619066/bash_history_dump.txt)
