### ISSUE TITLE
ruby: error while loading shared libraries: libssp.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ctuxboy** [skycocker/chromebrew#2967]
Hello,
After install Chromebrew, trying install a package:
`$crew install filezilla.rb`

But it gives an error:
**ruby: error while loading shared libraries: libssp.so.0: cannot open shared object file: No such file or directory**

trying reinstall, without luck.

How can i solve this problem?

My Chromebook:
Acer R13
ChromeOS 71.0.3578.94

**Comment by uberhacker** [comment]
Hey @ctuxboy: Thank you for reporting.  We are aware of the problem and currently working on a fix.

**Comment by ctuxboy** [comment]
Hi @uberhacker 
Okay ;-)

**Comment by uberhacker** [comment]
@ctuxboy: This issue should be resolved.  Let me know if you still have trouble.

**Comment by rsanchej** [comment]
Hi @uberhacker and @ctuxboy ,
I am having the same or similar issue!  How did it get fix?  What are the steps?
Thanks for the tip!

**Comment by JL2210** [comment]
Reinstall.

**Comment by uberhacker** [comment]
@rsanchej:  This issue usually happens when you `crew remove gcc7/8`.  Unfortunately, the only way to fix is to reinstall since ruby depends on gcc.  It would be nice if Chromebrew would prevent you from inadvertently removing dependency packages like other packages mangers.  There is [an issue for this](https://github.com/skycocker/chromebrew/issues/858).
