### ISSUE TITLE
selinux problem

### ISSUE THREAD

**Issue by jam7** [skycocker/chromebrew#303]
I've investigated selinux problem refered by #146 and #271.

In fact, Chromeos for ARM is distributed with /lib/libselinux.so.1.  Therefore, configure scripts decide to use selinux although system or toolchains doesn't contain selinux.h file.  As a result, `crew install` faults with following errors.

```
fileio.c:35:29: fatal error: selinux/selinux.h: No such file or directory
 #include <selinux/selinux.h>
```

It looks like x86_64 also has the identical problem, but only x86 doesn't.

I've checked binary chromebrew packages for all chipset but not found selinux.h.  So, I guess only x86 doesn't have /lib/libselinux.so* nor /usr/lib/libselinx.so*.  Is it possible to check it on x86 machines?  Thanks in advance.

**Comment by minektur** [comment]
Note that we have approximately the same problem with openssl - the libraries are on the system but the header files (the .h files) are not included.  We dont use selinux features in chromeos, so it seems reasonable to just disable the functionality in things that want to optionally link against it.

The other workable option would be to make a package that just installs the header files for the current version of the selinux libraries, kind of like we do with openssl.  Its a bit of a pain because at any time, google can update the library versions and we'll just have to react quickly.  Well, this isn't strictly true because sometimes when the library is update the abi remains the same...  but it can change and then we have to react.

In the case of vim... I'd personally just disable the selinux code and move on.

**Comment by lyxell** [comment]
I agree with @minektur 

I'll merge pull request #301 to disable selinux for vim as a temporary solution

**Comment by jam7** [comment]
Questions are:

- do we need to check this selinux problem whenever ppl send pull request?  Because it looks like problem for only arm and x64, so ppl working on x86 may send pull request without particular test.
- should we make selinux-devel package and try to add dependency for that for every PR?

If all shows the identical behaviors, this would not be the problem...

**Comment by jam7** [comment]
Or sure it is possible to maintain problems by this issue submissions.

**Comment by cstrouse** [comment]
Since the OS is busybox-based and selinux is disabled in the busybox build configuration I don't think it's a problem to just disable it in general.

**Comment by jam7** [comment]
@cstrouse I agree with you.  It's good excuse even the system doesn't use selinux.

**Comment by lyxell** [comment]
Closing as resolved.
