### ISSUE TITLE
[golang update] go 1.12 is released

### ISSUE THREAD

**Issue by nosarthur** [skycocker/chromebrew#3195]
https://blog.golang.org/go1.12

**Comment by JL2210** [comment]
Thank you for letting us know. Not sure if go is our highest priority right
now, but I imagine somebody may try to update it.

**Comment by nosarthur** [comment]
This is not urgent to me either. Maybe I will learn how to update it and hopefully create a PR

**Comment by uberhacker** [comment]
@nosarthur: Apply the attached patch and you can get credit for this update.
```
$ cd
$ git clone git@github.com:skycocker/chromebrew.git
$ cd chromebrew/packages
$ patch -p1 go.rb < ~/Downloads/go-1.12.patch.txt
```
[go-1.12.patch.txt](https://github.com/skycocker/chromebrew/files/2915843/go-1.12.patch.txt)

**Comment by JL2210** [comment]
He's not the one who wrote it, so why should he get credit?

**Comment by skiman6010** [comment]
@JL2210 Because we are trying to get new people involved to create, update and maintain packages so the work isn't all on the few tireless workers. The best way to get people involved is by letting them dip their feet in the water and not just pushing them into the ocean. 

@uberhacker has set up a nice way for @nosarthur to clone and see how the repo is laid out while also providing enough help in that patch to not mess anything up and also to learn how updates are applied. They obviously have some interest in golang or they wouldn't have notified us of the update. In that regard, allowing them to explore how packages are updated without completely jumping in seems like the best way to get more people involved. 

If you have a problem with that, you can PM us in Slack so we don't clutter this issue with more bickering. 

Thanks!

**Comment by JL2210** [comment]
You're right. Sorry.
