### ISSUE TITLE
[nano] Incorrect path in global nanorc

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#3325]
When you first open `nano` it complains that there are mistakes in `/usr/local/etc/nanorc`. Upon exit the following error is displayed:

```bash
chronos@localhost $ nano
Error in /usr/local/etc/nanorc on line 260: Error expanding /usr/share/nano/*.nanorc: No such file or directory
```
This should refer to `/usr/local/share/nano/*.nanorc`.

**Comment by uberhacker** [comment]
@cstrouse: I'm not noticing this.  What is your architecture?  ie. What is the output of `arch` and `nano -V`?

**Comment by JL2210** [comment]
Try removing and reinstalling `nano`.

**Comment by cstrouse** [comment]
That was on a fresh install of chromebrew and nano on Cloudready.

**Comment by cstrouse** [comment]
Closing since I can't reproduce.

**Comment by rakesh-9553** [comment]
Error in /etc/nanorc on line 237:

**Comment by satmandu** [comment]
What is the error you get?

**Comment by rakesh-9553** [comment]
Error in etc/nanorc on line 237

**Comment by rakesh-9553** [comment]
How can i solve this?

**Comment by satmandu** [comment]
@rakesh-9553 Please open a new issue for this, as this looks like it is a new unrelated issue.

**Comment by dwbapst** [comment]
I'm seeing this exact error whenever I use nano via gitbash on a Windows 10 machine, installed as part of the Git for Windows package of software. Version of nano is 5.8 (see below). Other Windows users in the same Software Carpentry workshop I am in are seeing the same error when calling nano. May be a problem with Git for Windows rather than nano *per se*, but I wanted to update the bug report here regardless.

```
$ nano --version
 GNU nano, version 5.8
 (C) 1999-2011, 2013-2021 Free Software Foundation, Inc.
 (C) 2014-2021 the contributors to nano
 Compiled options: --enable-utf8
 ```

**Comment by dwbapst** [comment]
Oh, this isn't even the nano repo. I apologize -- I am an idiot. This is unassociated with chromebrew.
