### ISSUE TITLE
package openssl_devel not found

### ISSUE THREAD

**Issue by finwo** [skycocker/chromebrew#335]
As the package name is appended with 'devel', this shouldn't come as a surprise to me, but the package has been removed on the master branch.

This shouldn't be a problem to me, as I don't depend on the package (non-devel requirements), but some unexpected behavior made chromebrew unusable:

Whenever I'm trying to update or upgrade, I get notified that the `openssl_devel` package was not found & it refuses to update/upgrade anything. Same thing goes for trying to remove the package, which is more of an issue.

The actual issue:
It is not possible to remove unknown packages after they've dissapeared from the package list. 

Suggested fix:
Keeping a copy of the package file in a local directory to indicate it as installed & track the installed version (I don't know how crew currently keeps track of that) & using that to run the 'remove' command could resolve this issue. It would then also be possible to show the currently installed version of a package, as a bonus feature. ( Almost like described in #332 )

**Comment by jam7** [comment]
That's very good point.  I didn't notice it.  Thanks.

For the remedy until the fix of this problem (I guess modification of crew is required), I'll send a PR to make a place holder for openssl_devel.  It's emptry package, so that if user performs `crew upgrade openssl_devel`, all files are removed and keep having empty openssl_devel package with a tag `removed`.  User can removed by hand too.

BTW, file might not be removed because of upgrade bug.  Crew upgrade issues `crew remove` without sudo.

**Comment by lyxell** [comment]
Merged the temporary fix. Working on a permanent solution.

**Comment by lyxell** [comment]
There's a pending pull request which resolves this issue.

**Comment by thedamian** [comment]
pkg_config removed in pull https://github.com/skycocker/chromebrew/pull/311
