### ISSUE TITLE
The ruby version in install.sh does not reflect the one in ruby.rb

### ISSUE THREAD

**Issue by lyxell** [skycocker/chromebrew#340]
The ruby version in install.sh is `2.0.0p247`, while the one in ruby.rb is `2.0.0p247-chromeos1`.
This results in crew wanting to upgrade ruby when running `crew upgrade` on a fresh install even though ruby is not outdated.

**Comment by thedamian** [comment]
I think this was done because of a typo and to help people wth older versions.

I also believe that ruby has always had an older version with the install.sh than with the package because we didnt want to recreate all the great work skycoker did but still wanted users to be able to upgrade to the latest and greatest.

**Comment by thedamian** [comment]
I see that it was done when adding support for x64
https://github.com/skycocker/chromebrew/commit/17e8cf16ee1936b0b10f07fb2888503364fa9bfb

do you want to put a PR to push it (and Ncurses) back to without the '-cromeos1' since you found this? @lyxell
