### ISSUE TITLE
Cannot install mandb package

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#342]
```
configure: error: Package requirements (libpipeline >= 1.4.0) were not met:

No package 'libpipeline' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libpipeline_CFLAGS
and libpipeline_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
mandb failed to install: `./configure --with-systemdtmpfilesdir=/usr/local/lib/tmpfiles.d --disable-cache-owner --with-pager=/usr/local/bin/less` exited with 1
```
Missing dependency in mandb.rb?

**Comment by uberhacker** [comment]
OK, I checked `mandb.rb` and it has `depends_on 'libpipeline`.  I already have the `libpipeline` package installed at it says version 1.4.1.  Why does `mandb` think I don't have `libpipeline` installed?

**Comment by jam7** [comment]
Did you try new pkgconfig, #341?  It will solve your problem.

I didnt' try mandb without new pkgconfig, so I'm not perfectly sure what the source of this problem, but I guess it is caused by old pkgconfig.  Old pkgconfig searches only either of /usr/local/lib32 or lib64 although we have libpipeline in /usr/local/lib.

You can solve this by setting `export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig:/usr/local/share/pkgconfig` or install new pkgconfig at #341.

I'm using new pkgconfig and `crew install mandb` works well on both armv7l and x86_64.

**Comment by uberhacker** [comment]
@jam7: Yeah, that fixed it.  Another case of my `/usr/local/lib/crew/packages` directory not being updated!  Thanks

**Comment by jam7** [comment]
@uberhacker you are welcome.  it is not surprising me since I updated pkgconfig after you filed this issue.  :)
