### ISSUE TITLE
Package bundles?

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#350]
Has the topic of package "bundles" or "collections" been discussed yet?  Basically, the idea is to create a collection of packages and install each as one complete install.  Essentially, it would, in theory, work like a shell script something like below:
```
#!/bin/bash
crew install sqlite
crew install nginx
crew install php7
```
This would install a SNAP (aka Sqlite, Nginx And Php) stack bundle.

**Comment by kirbyfan64** [comment]
You mean like [this](https://github.com/skycocker/chromebrew/blob/master/packages/buildessential.rb)?

```ruby
require 'package'

class SNAP < Package
  version '1.0'

  is_fake

  depends_on 'sqlite'
  depends_on 'nginx'
  depends_on 'php7'
end
```

**Comment by uberhacker** [comment]
Perfect!

**Comment by thedamian** [comment]
@kirbyfan64 that solved the problem well but it would be hard to find or for someone to know that THAT is what they're installing.

I like the idea of bundles (and I like kirbyfan64's solution) but I think "findablility" would be a problem as new users wouldn't know that "mean.rb" is the MEAN stack or what ever. 

Now if you DO submit that package kirbyfan64... I'll approve it because it DOES add value. I just want the discussion to continue.

**Comment by uberhacker** [comment]
@thedamian: I have an issue (see #332) in the queue that would help make it easier for folks that are looking to install new packages.  If we add descriptions on all the packages (or bundles?), that will be very helpful (for mere mortals).
Thanks

**Comment by thedamian** [comment]
I love it.

who's going to take the lead on this?

I'll volunteer to change our http://skycocker.github.io/chromebrew/ to add a search or just pull from that .json file and list all the packages available and that short description.
