### ISSUE TITLE
Any way to install tar.gz archives directly?

### ISSUE THREAD

**Issue by Absence209** [skycocker/chromebrew#3621]
## Before you submit an issue
Is there any way to directly install a tar gz command with the crew command even if it is not in the official packages directory?

## Description
Like in dpkg for debain you can install a package like so:

```shell
dpkg -i /path/to/Debian/package.deb
```

So is there any alternative to that like something along the lines of:
```shell
crew --install-from-local /path/to/tar/archive.tar.gz
```

**Comment by cstrouse** [comment]
What are you trying to achieve? A bit more info will help us guide you to a solution.

You can already put whatever you want into `/usr/local` and make use of it.

**Comment by uberhacker** [comment]
@Absence209: The main issue with tarballs is they need to include the Chromebrew specific metadata about the packages so it can track the files for searching and removal with the crew command.  If your packaged tarball includes this metadata, then you could safely install this way.  This is the way all the binary packages are built that are currently available.  In order to do what you suggest, we would need to determine if the package is source code or binary and that is probably more trouble than it's worth to do something like this.

**Comment by Absence209** [comment]
> @Absence209: The main issue with tarballs is they need to include the Chromebrew specific metadata about the package so it can track the files for searching and removal with the crew command. If your packaged tarball includes this metadata, then you could safely install this way. This is the way all the binary packages are built that are currently available. In order to do what you suggest, we would need to determine if the package is source code or binary and that is probably more trouble than it's worth to do something like this.

Is there any tutorial on how to make crew pacakges?

**Comment by uberhacker** [comment]
Sure, check out the [wiki](https://github.com/skycocker/chromebrew/wiki/Creating-a-package).
