### ISSUE TITLE
[pcre] checksum mismatch

### ISSUE THREAD

**Issue by cstrouse** [skycocker/chromebrew#3968]
@vincowl This is why we need to make sure and test updates before opening PRs.

```bash
pcre: The PCRE library is a set of functions that implement regular expression pattern matching using the same syntax and semantics as Perl 5.
http://pcre.org/
version 8.44
Precompiled binary available, downloading...
##################################################################################################################################### 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Installing...
Performing post-install...
Downloading source...
##################################################################################################################################### 100.0%
Checksum mismatch. :/ Try again.
```

**Comment by cstrouse** [comment]
Disregard. Appears it was a network-related issue as it worked on a second attempt.

**Comment by vincowl** [comment]
As said, PR are tested on my machine. Maybe it is not enough and should be tested on other archs. That's why I suggested to create a CI build machine that would test this automatically once PRs are submitted. I am not sure how I can run docker on my machine and it would be better to centralize it instead of deploying this validation toolchain on users own machines
