### ISSUE TITLE
Chromebrew installation halts on Acer C7 due to Python3 installation error

### ISSUE THREAD

**Issue by heroldev** [skycocker/chromebrew#4056]
## Description
Chromebrew install script halts after finishing the installation of Python3, as pip3 fails to execute because glibc 2.27 is missing. Chromebrew works, but updating to the most recent version causes crew to fail entirely.

If you executed a specific command (in this case, the install command):
`curl -Ls git.io/vddgY | bash' or 'crew install python3'

Output:
```Upgrading pip...
/usr/local/bin/python3.8: /usr/local/lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib64/libpython3.8.so.1.0)
/usr/local/bin/python3.8: /usr/local/lib64/libc.so.6: version `GLIBC_2.26' not found (required by /usr/local/lib64/libpython3.8.so.1.0)
/usr/local/bin/python3.8: /usr/local/lib64/libc.so.6: version `GLIBC_2.27' not found (required by /usr/local/lib64/libpython3.8.so.1.0)
python3 failed to install: `pip3 install --upgrade pip` exited with 1
```

## Versions and system information
chromebrew: `1.3.6`

ChromeOS: 
```
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={9D137383-EB72-4BA9-A523-91AC0853F8AD}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={9D137383-EB72-4BA9-A523-91AC0853F8AD}
CHROMEOS_RELEASE_BOARD=parrot-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=67
CHROMEOS_RELEASE_BUILDER_PATH=parrot-release/R65-10323.67.9
CHROMEOS_RELEASE_BUILD_NUMBER=10323
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=65
CHROMEOS_RELEASE_DESCRIPTION=10323.67.9 (Official Build) stable-channel parrot 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=9
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10323.67.9
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10323.67.9
```

Model: PARROT JUNGLEFOWL A-C 9519

Architecture: x86_64

## Addtional information
I used the script from uberhacker's fork of this project to install chromebrew, as using the script from this repo causes the install script to fail after installing libssh2 (same error outputted).

The issue seems to stem from glibc 2.23 being installed on my machine instead of glibc 2.27, which is what most packages seem to be built with now. Is there any way to update glibc to work with my machine?

I've tried compiling from source via 'crew build glibc' and outputs 
```
These critical programs are missing or too old: ld make
Check the INSTALL file for required versions.
glibc failed to build: ../configure --prefix=/usr/local --libdir=/usr/local/lib64 --with-headers=/usr/local/include --disable-werror --disable-sanity-checks --enable-shared --disable-multilib --enable-obsolete-rpc libc_cv_forced_unwind=yes libc_cv_ssp=no libc_cv_ssp_strong=no exited with 1
```

---

**Comment by uberhacker** [comment]
@heroldev: It looks like your problem is Chromebrew is looking for glibc 2.23.  You are also on ChromeOS release 67.  The current stable release is 81.  Has your Chromebook reached EoL support?  If this is the case, the only way to make the install work is to grab a commit prior to when we switched from glibc 2.23 to 2.27.

**Comment by cstrouse** [comment]
You may also be able to upgrade to 81 by using Arnold the Bat's vanilla image and a tool called brunch.

**Comment by heroldev** [comment]
Acer C7 is currently EOL. @uberhacker when was Chromebrew updated to use 2.27 over 2.23? 
wouldn't the issue regarding glibc be with the package itself, then?

checking glibc on my C7 shows that 2.23 is installed, rather than 2.27.

**Comment by JL2210** [comment]
From my experience in the past, the glibc package creates symlinks to the system libraries because otherwise all of the programs you try to run segfault. Not sure if this is the case now, but it probably is. Anyway, you're probably not going to have luck with that; most of the old package binaries have been removed by now.

**Comment by uberhacker** [comment]
Chromebrew was updated to 2.27 when ChromeOS 72 was released.  If you checkout a commit from this repo before Feb 22, 2019 (See #3188), you can use that install.sh to get a working Chromebrew.  However, you won't be able to update to glibc 2.27 since ChromeOS installs all the libraries in a read-only directory (which is glibc 2.23, in your case).  If you don't mind the possibility of bricking your device, you can try to do what @cstrouse suggested and reformat your hard disk and install the operating system, essentially wiping out the previous ChromeOS.

**Comment by ThatGeekyWeeb** [comment]
There is an issue with the python package for any not stable devices, the fix is to grab a old `.rb` for python, 3.6.X seems to work. This is also many months old, and can likely be closed due to lack of response @uberhacker.

**Comment by madhits** [comment]
How do I crab a commit from chromebrew when it was on glibc version 2.32? Maybe I can figure that out...

**Comment by satmandu** [comment]
Try `crew update ; yes | crew upgrade ; crew install python3`

**Comment by madhits** [comment]
> Try `crew update ; yes | crew upgrade ; crew install python3`

Thanks I'll try that...

**Comment by madhits** [comment]
> Try `crew update ; yes | crew upgrade ; crew install python3`

Thanks I tried this, It did not work. My issue is with pulseaudio which says it needs glibc 2.34 and I only have glibc 2.32. VLC wont start without pulse audio and pulseaudio wont start with glibc being updated, which is impossible under my current chrome OS because I am stuck with no further updates. So is there a workaround? THANKS

**Comment by satmandu** [comment]
Does crostini work for you?

**Comment by madhits** [comment]
Nope I wish. I don't have virtualization on my CPU. It's an atom n455 gma3150.

**Comment by Mia-Rain** [comment]
what chrome os do you have?
your best bet would be to hand roll your own chroot and fight sommelier tbh
or use mr.chromebox's script and leave chrome os since theres a 100% chance you wont have gpu acceleration and it'll make xorg apps horrific to use
a small selection of native wayland apps might be able to inject themselves into the wayfire compositor but I wouldn't bet on it, ive only seen it happen once

**Comment by Mia-Rain** [comment]
if you can leave chromeos use legacy bios and if you cant then try a chromeos upgrade using brunch
> find a chromebook with the same cpu & gpu vendor and use the chromium images from arnold the bat to make a bootable chromeos image and upgrade to that using the brunch method  
> see this for more info most likely
>> https://github.com/sebanc/brunch/discussions/712

**Comment by Mia-Rain** [comment]
otherwise you'll be stuck fighting chromebrew for a while since glibc 2.32 is long gone and glibc linking will likely be a massive issue since you can't actually upgrade the glibc on the system without destroying chromeos

**Comment by madhits** [comment]
> otherwise you'll be stuck fighting chromebrew for a while since glibc 2.32 is long gone and glibc linking will likely be a massive issue since you can't actually upgrade the glibc on the system without destroying chromeos

I've used brunch in the past but can't find a match for my system with GMA 3150, it would be a long dead system prob chrome os prior to 90. I'm on cloudready 96, runs great. Maybe I can just try a few, lots of research but I need a chrome os past 96 to get a new glibc after 2.34..

**Comment by Mia-Rain** [comment]
ik this is a month late but anything with the same core architecture and gpu provider will work fine with brunch

**Comment by madhits** [comment]
> ik this is a month late but anything with the same core architecture and gpu provider will work fine with brunch

I had no such luck, brunch would not boot, after build. Any suggested brunch version? I have had a system that would only allow install with an older brunch version (ie 85, which later updated fine to 100). So if you have a suggested brunch version that might be it to boot. For now I've got the system on AntiX Linux and it's surprisingly fast.
