### ISSUE TITLE
[Question] Flatpak?

### ISSUE THREAD

**Issue by sos-michael** [skycocker/chromebrew#4243]
Hopefully this doesn't come across as rude or presumptuous!  

Like it says on the tin, I'm wondering if any thought has been given to maintaining a flatpak package?

Thanks.

**Comment by uberhacker** [comment]
@sos-michael: flatpak is a package manager, not necessarily a package.  If you can come up with a way to integrate flatpak packages into Chromebrew, a pull request is welcome.

**Comment by vincowl** [comment]
@sos-michael @uberhacker see our discussion about that on slack channel (messages published on 04/21/2020). I managed to create a package for flatpak. The problem is that we cannot run apps due to `Failed to mount tmpfs` and `error: ldconfig failed, exit status 256`  errors... This forces users to disable rootfs verification which creates a security breach. 
@uberhacker you also mentioned that it was a "competitor" of chromebrew... 😉

**Comment by sos-michael** [comment]
@vincowl This is actually what I was wondering about! The container nature of flatpak seems to be a real trip up to getting it working. 

I'm not actually part of the slack group, has thought been put into other types of containers that have containerizing as an option instead of a requirement? I realize there is this notion of it being a competitor of sorts, but that really misses the mark in my mind. Many distros keep their native package management along side this more universal ones. Having the flexibility is nice, plus it really expands the available options for software.

The other gotcha would likely be ensuring the Sommelier hooks are setup correctly for any app that is installed via flatpak.

**Comment by vincowl** [comment]
@sos-michael All I've ever tried was flatpak and docker (which works but I find it still too slow and not stable enough to be used reliably). What were you thinking about mentioning "optional containerization" ?

I fully agree having this option would be a good thing : offering other approaches is often valuable. But to be honest, this also leads to several troubles : man could be tempted to upgrade flatpak instead of other classical packages. I think efforts should rather be put on upgrading sommelier (hell to compile !), improve dependencies handling, testing, and so on.... This actual solution is light, effective and simple and should stay as is in a user point of view. When I worked on flatpak, I mainly wanted to run my own docker containers (initially docker containers) or avoid dependencies upgrade steps, or avoid compilation of complex apps. But finally, I recognize that I don't need these apps or managed to pack them as a chromebrew package. So... I let this idea away and did not try to play with chromeOS security layers which is not a brilliant idea I think ;-)

If you want, I can share these files if you want to play with flatpak

**Comment by saltedcoffii** [comment]
Flatpak is now available as a package. This can be closed @uberhacker
