### ISSUE TITLE
Add -pipe

### ISSUE THREAD

**Issue by saltedcoffii** [skycocker/chromebrew#4948]
Because my ruby skills are still much too basic to do this efficiently, would somebody mind adding:
```shell
CFLAGS=-pipe
CXXFLAGS=-pipe
```
and optionally for the fortran compilers:
```shell
FCFLAGS=-pipe
FFLAGS=-pipe
```
This causes gcc to prefer memory instead of temporary files, seriously speeding up compilation times, while having no effect on the produced machine code. (On some computers with next to no memory, this can cause gcc to get killed by the kernel, but considering that basically all chromebooks have at least 2GB of memory and some swap, this won't be an issue.)

**Comment by satmandu** [comment]
Maybe we could add this to CREW_OPTIONS?

Also maybe we could do something like ```CFLAGS += ' -pipe'``` so that we can just add new CFLAGS as necessary?

Thoughts @uberhacker @supechicken ?

Also, some of the packages I have put together DO need more memory for compilation (especially when they use ```-flto```, and will NOT compile on machines with less than 4Gb of memory. Normally this is fine since the docker images run on machines with > 4Gb of RAM.

**Comment by uberhacker** [comment]
If you think it's something that should be included on every compile then by all means, please add to `CREW_OPTIONS`.

**Comment by satmandu** [comment]
So here's the rub.  We can add CFLAGS like ```-pipe``` to CREW_OPTIONS, but that would override other CFLAGS given elsewhere in the package file, since ```+=``` doesn't work.

i.e., this is what happens with ```CREW_OPTIONS = "--prefix=#{CREW_PREFIX} --libdir=#{CREW_LIB_PREFIX} --mandir=#{CREW_MAN_PREFIX} --build=#{CREW_BUILD} --host=#{CREW_BUILD} --target=#{CREW_BUILD} CFLAGS+=' -pipe' CXXFLAGS+=' -pipe' FCFLAGS+='-pipe' FFFLAGS+=' -pipe'"```
```
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
configure: error: invalid variable name: `CFLAGS+'
zsh failed to install: `./configure --prefix=/usr/local --libdir=/usr/local/lib64 --mandir=/usr/local/share/man --build=x86_64-cros-linux-gnu --host=x86_64-cros-linux-gnu --target=x86_64-cros-linux-gnu CFLAGS+=' -pipe' CXXFLAGS+=' -pipe' FCFLAGS+='-pipe' FFFLAGS+=' -pipe'` exited with 1
```

So probably best just to drop it into package scripts... (I'm already adding ```-flto``` as I go, so maybe this isn't too much of a problem.

However, we COULD add this to MESON options thus:
```
CREW_MESON_OPTIONS = "-Dprefix=#{CREW_PREFIX} -Dlibdir=#{CREW_LIB_PREFIX} -Dmandir=#{CREW_MAN_PREFIX} -Dbuildtype=release -Dc_args='-fuse-ld=lld -pipe' -Dcpp_args='-fuse-ld=lld -pipe'"
CREW_MESON_LTO_OPTIONS = "-Dprefix=#{CREW_PREFIX} -Dlibdir=#{CREW_LIB_PREFIX} -Dmandir=#{CREW_MAN_PREFIX} -Dbuildtype=release   -Dcpp_args='-flto -fuse-ld=gold -pipe' -Dcpp_link_args='-flto' -Dc_arg
s='-flto -fuse-ld=gold -pipe' -Dc_link_args='-flto'"
```
