### ISSUE TITLE
[Enhancement] add self.remove package function

### ISSUE THREAD

**Issue by saltedcoffii** [skycocker/chromebrew#5164]
A self.remove package function would be run right before the package is uninstalled during `crew remove`. 
I'd like this to run on the flatpak package:
```ruby
  def self.remove
    system "flatpak remove --all"
  end
```
I'm sure this has ample other uses, such as removing configuration files, especially in the home directory. 

Rust's might be able to look like:
```ruby
  def self.remove
    system "rm $HOME/.cargo"
  end
```

and Atom's can look like:
```ruby
  def self.remove
    system "rm $HOME/.atom"
  end
```

This can also be useful for displaying messages to remind the user to do something.
For example, with flatpak:
```ruby
  def self.remove
    puts
    puts "Flatpak user data is stored in ~/.var/app/. To save space on your machine, you can remove this data if you don't need it.".lightblue
    puts "rm ~/.var/app/*"
    puts
  end
```

I'm not skilled enough with ruby to do this, however if someone could work on this, that would be amazing.

**Comment by kjperkin** [comment]
I like your last use-case a lot. I think it embodies a good rule of thumb, which is: only touch what you own unless explicitly asked to do otherwise. A hook like this would be great for reminding people about stuff they *might* want to clean up. If/when we later have have more advanced options we can give to `crew remove`, I imagine we could then pass those into this hook and it could prompt about or take more aggressive action.

**Comment by supechicken** [comment]
See #4791
