### ISSUE TITLE
tcpstat source code is unavailable

### ISSUE THREAD

**Issue by jam7** [skycocker/chromebrew#542]
tcpstat source code, http://www.frenchfries.net/paul/tcpstat/tcpstat-1.5.tar.gz, is unavailable for almost one month.  On the other hand, https://github.com/jtt/tcpstat is available, but there is no released tar files.

Is there any good way to modify tcpstat.rb?

**Comment by cstrouse** [comment]
Maybe grab a tarball from a specific commit SHA1.

On Feb 25, 2017 6:32 AM, "Kazushi (Jam) Marukawa" <notifications@github.com>
wrote:

tcpstat source code, http://www.frenchfries.net/
paul/tcpstat/tcpstat-1.5.tar.gz, is unavailable for almost one month. On
the other hand, https://github.com/jtt/tcpstat is available, but there is
no released tar files.

Is there any good way to modify tcpstat.rb?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/skycocker/chromebrew/issues/542>, or mute the thread

**Comment by jam7** [comment]
I've just noticed this launchpad, https://launchpad.net/ubuntu/+source/tcpstat/1.5-8, contains the original source code at below.

 - https://launchpad.net/ubuntu/+archive/primary/+files/tcpstat_1.5.orig.tar.gz

File name is modified but the sha1sum is identical.  Please update it if you can.  Thanks.

**Comment by cstrouse** [comment]
I'm gonna go back to stable channel this evening and will update.

**Comment by jam7** [comment]
closed in favor of #598
