### ISSUE TITLE
Automatic build binary package feature

### ISSUE THREAD

**Issue by jam7** [skycocker/chromebrew#552]
Do we like to have something like the topic?  It creates binary package for your architecture automatically from a package's `.rb` file.  For example,
```
$ crew build git
...
$ ls
git-2.11.0-chromeos-armv7l.tar.xz
git-2.11.0-chromeos-armv7l.tar.xz.sha1
```
We can build any binary packages easily with this.

It is possible to use this to create all binary packages of all `.rb` files if you have time and disk space for that. :)

I've modified crew to do that.  I'd like to hear any opinions about something like this feature before submitting a PR.  For example, is `build` command name common for something like this purpose?  Thanks.

**Comment by finwo** [comment]
Yes, I would like this feature.

---

An extra request though: Would it be feasible to create binary packages out of structured folders (as we would when building packages now) by providing a directory path (of which the name is not a known package name)?

Binary package building would become a lot faster with this, as one would be able to simply download all required binary files & point crew to the directory for each architecture.

**Comment by jam7** [comment]
It uses original mechanism for compile, so it extracts files under /usr/local/tmp/crew and build binaries there.  It moves files to /usr/local/tmp/crew/dest and modified crew make binary package file at working directory even if it is your home directory.

Does this what you want?

You explanation sounds like you would like to gather binary package files in particular directory and install packages from there instead of downloading...

**Comment by finwo** [comment]
Your interpretation of my explanation is almost correct. I do want to gather the files in a particular directory.

Instead of installing from there, I'd like to build the arm, x86 & x86_64 archives based on the directories. ( automatically build the dlist & flist, archive them & output the checksums in separate files ).

This removes some manual steps from creating binary packages. I could try to build an example script for it, but I'm not that experienced with Ruby.

**Comment by jam7** [comment]
Closing since #573 is merged.
