### ISSUE TITLE
The "Architecture" section of chromebrew's issue template does not give the true architecture of the system.

### ISSUE THREAD

**Issue by QueenPew** [skycocker/chromebrew#5774]
## Description
Some Chromebooks (such as mine) have a 64-bit kernel with a 32-bit userland (the packages are 32-bits). This makes `uname -m` inaccurate since it only gives the architecture of the system.
For example, here's the output of `uname -m`
```shell
$ uname -m
aarch64
```
Now, if we get the LONG_BIT (the value that reports the maximum value of a bit) variable for my system and/or the file type of `/sbin/init`, we'll find that the system is 32-bit.
```shell
$ getconf LONG_BIT
32
$ /sbin/init
/sbin/init: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[xxHash]=a1367955f0a1e85a, stripped
```
## Versions and system information
Model: Lenovo C330

Architecture: `uname -m`
64-bit ARM kernel with 32-bit userland
## Additional information
This took way too long to find.

What I think needs to be done:
- [ ] include  `getconf LONG_BIT` and/or `file /sbin/init` with `uname -m` in the architecture section of Chromebrew's issue template section.

**Comment by heavygabriel** [comment]
Also, `crew const` returns `uname -m`(post above explains why `uname -m` is not a good idea for some systems)  instead of the userland architecture for the `ARCH` const.

**Comment by uberhacker** [comment]
@heavygabriel: It's well known that aarch64 Chromebooks use a 32-bit userland.  In fact, the Google team working on Chrome OS has not spent enough time and effort yet to integrate a 64-bit userland.  There is a lot of talk but not much action so far probably because the task is too daunting. :)

**Comment by satmandu** [comment]
@heavygabriel What does `uname -a` give you on your machine?

If you look [here](https://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices) you will notice that for the arm based machines, the `Kernel ABI` tends to be `aarch64` but as of yet for all of those machines, none are on a `User ABI` of `aarch64`, instead sticking to `armv7l` (well, with hard float).

This is of course irritating because debian supports aarch64 userland, Raspberry Pi almost officially supports it now too, and arm64 has been around for many years.

(I build packages for the arm Chromebooks on a VM on my 64 bit RPI4.. though if I had a M1 mac, I'd put Linux on one of those and build the packages in a VM on those devices because it would be so much faster...)

**Comment by satmandu** [comment]
(The big issue though is that even though you have a 64-bit kernel, you are invoking Chromebrew from the ChromeOS armv7l userland, and I don't think you can invoke aarch64 apps from an armv7l userland.)

**Comment by heavygabriel** [comment]
> What does uname -a give you on your machine?

```shell
$ uname -a
Linux localhost 4.19.176-11263-g91924d8d61fa #1 SMP PREEMPT Tue Apr 27 20:19:33 PDT 2021 aarch64 GNU/Linux
```
> (The big issue though is that even though you have a 64-bit kernel, you are invoking Chromebrew from the ChromeOS armv7l userland, and I don't think you can invoke aarch64 apps from an armv7l userland.)

You are correct @satmandu, aarch64 apps can't run on an armhf/armv7l userland. Also, you cannot build aarch64 apps on an armhf/armv7l compiler (the joys of kernel autodetect!) (this is an issue because some packages will detect an aarch64 kernel, try to build an aarch64 version but fail because GCC's armhf version has different functions than the aarch64 one, resulting in weird weird weird errors from GCC).
