### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by jrschumacher** [skycocker/chromebrew#60]
When trying to change permissions

```
localhost / # whoami
root
localhost / # ls -al /etc/shells
-rw-r--r-- 1 root root 128 Oct 28 09:53 /etc/shells
localhost / # chmod 664 /etc/shells
chmod: changing permissions of ‘/etc/shells’: Read-only file system
```

**Comment by tommyvanduyne** [comment]
I think I have a solution:
I ran this code,  
    sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification

and I got this returned:
<<ERROR: YOU ARE TRYING TO MODIFY THE LIVE SYSTEM IMAGE /dev/sda.
  The system may become unusable after that change, especially when you have
  some auto updates in progress. To make it safer, we suggest you to only
  change the partition you have booted with. To do that, re-execute this command
  as:
    sudo ./make_dev_ssd.sh --remove_rootfs_verification --partitions 4
  If you are sure to modify other partition, please invoke the command again and
  explicitly assign only one target partition for each time  (--partitions N )
ERROR: IMAGE /dev/sda IS NOT MODIFIED.>>

So I then ran:
    sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions 4
and restarted my computer.

This apparently unlocks the read-only root filesystem for ChromeOS and allows you to modify root level programs and stuff.  However,  if you do unlock the the read-only root filesystem, you will need a recovery image to switch back to normal mode because the root filesystem will no longer be verifiable. 

source: http://www.chromium.org/chromium-os/poking-around-your-chrome-os-device

**Comment by skycocker** [comment]
It's all about chrome os, not chromebrew. Closing.

**Comment by jrschumacher** [comment]
@tommyvanduyne thanks for the tips
