### ISSUE TITLE
Some sommelier processes failed to start after update

### ISSUE THREAD

**Issue by krome-3k** [skycocker/chromebrew#6117]
Hi,
I am getting "some sommelier processes failed to start" after my ARM64 chromebook updated to Version 92.0.4515.162. Please help. 
Thanks in advance

**Comment by uberhacker** [comment]
@krome-3k: I have release 92 installed on my aarch64 Chromebook and sommelier is working fine.  You could try:
```
source ~/.bashrc && restartsommelier
```
If that doesn't work, try restarting your crosh session.  If you still have trouble, then try:
```
crew reinstall sommelier -s && restartsommelier
```
Hopefully, the final solution is not necessary.  Another thing you could try is rebooting your Chromebook.

**Comment by krome-3k** [comment]
@uberhacker : thanks man.. reinstalling did the trick. I am trying to install linux in my chromebook(not in a chroot) but both ubuntu server arm64 iso and debian arm64 iso refuse to boot from the usb with a beep. Can you please help me with this?

**Comment by uberhacker** [comment]
@krome-3k: Glad you were able to get sommelier working.  That tells me the arm binary is corrupt.  cc: @satmandu.  I don't think you will want to install Ubuntu server on your Chromebook.  First off, Chrome OS is already Linux and secondly, you probably already have most of the tools you would need in this project (which compile apps natively to Chrome OS).  I might suggest you try Linux Apps (aka Crostini) which runs Debian in a VM of sorts.  Of course, this is assuming your Chromebook supports it.  Otherwise, your Chromebook probably doesn't have enough horsepower anyway.

**Comment by krome-3k** [comment]
@uberhacker i did try crostini and crouton but they weren't impressive. You are right it doesnt have enough horsepower but wont removing chromeos and installing an arm64 distro make it more capable? I also tried installing archlinux on a usb with instructions from archlinuxarm.org for a dual boot scenario but all i got is a blank screen. Thanks anyway!

**Comment by uberhacker** [comment]
Sorry, I didn't realize you wanted to replace Chrome OS.  I imagine your issue is due to hardware incompatibility.  You will need to look up your hardware specs and see if any of the alternate OSes can be installed.  Dual-booting is probably not practical unless you have at least 16 gb of free space to partition off on your disk.

**Comment by krome-3k** [comment]
Yeah.. nothing available for my hardware yet, thanks. Should i close this issue?

**Comment by uberhacker** [comment]
You can leave it open since I suspect the arm binary is corrupt.  We can close it out after a new binary PR is generated.

**Comment by krome-3k** [comment]
Okay.. thanks!

**Comment by satmandu** [comment]
Please see if the binary in https://github.com/skycocker/chromebrew/pull/5922 works?
