### ISSUE TITLE
This isn't in the spirit of homebrew or linuxbrew .... I don't just understand the point of eudev ..... but about 90% of the packages (which don't work, and couldn't work in the latest versions of chrome)

### ISSUE THREAD

**Issue by chromakey-io** [skycocker/chromebrew#6118]
This is just a poor attempt at making crouton in users-pace, and crouton has been replaced by the official "crostini" which works rather well.  There's no need for the crouton project beyond the ego of the maintainers.

Which begs the question, why are there so many packages that CLEARLY shouldn't exist in a project named after homebrew.  I mean there's not even multiple versionings of major development tools like python (no 2.7 and the latest 3.x don't count), ruby, and node.js .... so what use is this to an ACTUAL developer?

It needs a reboot.  I don't especially want to do it, and if I do there'll be like 5 packages ..... sooo I'd need some help, and by help I mean I'd just be the benevolent dictator and I'd let y'all do the work on the packages you want and need and I'd reject things like minecraft, esoteric window managers, and icon styles.  I'd do python versions 3.x (all of them) .... and openssh (properly) but that's about it.

Check out my branch.   I'm going to strip it down to about 5 packages that I use .... any-one else with similar feelings is welcome to come along.  I just need a catchy name.  chrome-dist short for chrome-distillery

**Comment by daemonspudguy** [comment]
What are you talking about?

**Comment by uberhacker** [comment]
As the unofficial benevolent dictator of this project, there are some basic principles you CLEARLY don't understand.  This project is nothing like Crouton.  In fact, it's not a separate operating system and doesn't require a VM.  The goal of this project is to enable users to compile programs native to Chrome OS and avoid the overhead of projects like Crouton or Crostini.  On Chromebooks with low end resources, this is especially important.  You are the first to complain about not having multiple versions of Python and Ruby.  There are several ways to install Node.js with any version you want.  Check out the nvm and nodebrew packages.  If you want to get involved and help improve this project, we are very welcoming.  But talk is cheap.

**Comment by daemonspudguy** [comment]
Besides, not all Chromebooks even work with Crostini or have enough space for a chroot of Debian. And some people just don't need a full container of Debian to do what they want. This project is geared towards those users.




> As the unofficial benevolent dictator of this project

Brilliant!

**Comment by chromakey-io** [comment]
crouton isn't an "operating system" it's just a chroot environment.  It's exactly the same thing you're doing here, just you know ... not as hap-hazardly.


Any-how.  I'm forking this .... with the intention of creating a project geared towards DEVELOPERS like the namesakes you'v missused ... homebrew and linuxbrew.

Have a nice day.

**Comment by daemonspudguy** [comment]
You don't even seem to understand what a chroot environment is. It is an entire operating system being bootstrapped on top of the current one. Also, homebrew isn't "for developers" exclusively. And the name Chromebrew would still be appropriate because it uses the same methods of packaging and most of the same format as Homebrew does. Also also, creating a chroot of Debian brings the entire system Userland, whereas Chromebrew only installs what's needed for what you want to install. It takes an entirely different approach to Crouton, which again bootstraps a full Debian system.

**Comment by daemonspudguy** [comment]
Both have use cases, I'm not denying that.

**Comment by chromakey-io** [comment]
a chroot of debian minimal should be a couple 100mgs.   If your argument for creating what you did here is that Coruton's chroot is too big.

You should have just created a smaller one.

**Comment by uberhacker** [comment]
@chromakey-io:  There appears to be a fundamental misunderstanding of how this project works.  The main difference between Crouton and this project is we work with the existing Chrome OS.  Besides eudev (which you have the option to not install BTW), what makes it a disaster?  We are simply building upon the existing infrastructure rather than using an entirely different distro or operating system and all the overhead that comes with it.  If your beef is with the inability to install different versions of compilers and interpreters, you are welcome to help make it better.  But just bashing the project and forking it to make your own (which you totally have the option to do) is not being constructive or helpful to others.

**Comment by daemonspudguy** [comment]
> Or bootstrap DSL

Yes, because bootstrapping a Linux distro last updated 13 years ago will definitely be useful and not at all useless for development.
