### ISSUE TITLE
BSD-2 Clause licence violation

### ISSUE THREAD

**Issue by chromakey-io** [skycocker/chromebrew#6124]
Your work in general is a derivative of homebrew.

Though your "packages" / "casks" / "recipes" are not even derivations.  They remain exact copies of the code that exists in homebrew.

BSD-2 clause isn't that complex.  You can change your likenesses for any new code.  You can't change it for the code you haven't modified at all........ and even for derivative code you can't leave out the copyright.  ALL RIGHTS RESERVED.  Is not hard to understand.

**Comment by chromakey-io** [comment]
Copyright (c) 2009-present, Homebrew contributors
All rights reserved.

**Comment by uberhacker** [comment]
We're not like Homebrew and nothing is an exact copy.  We don't have casks or recipes; only packages.  There are plenty of things I don't like about the way they package their apps and this project tries hard NOT to be like them.  Instead of trolling, why don't you provide a pull request to fix something?
