### ISSUE TITLE
installation procedure bit rubbish

### ISSUE THREAD

**Issue by Unixware** [skycocker/chromebrew#6484]
## Before you submit an issue
Please look up our issues, maybe your problem was mentioned before.

## Description
torbrower package is BROKEN
in fact the installation starts , downloads a heck of packages then 
displays this
Performing pre-flight checks...
No precompiled binary available for your platform, downloading source...
curl: (6) Could not resolve host: www.torproject.org
Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
curl: (6) Could not resolve host: www.torproject.org
Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
curl: (6) Could not resolve host: www.torproject.org
Warning: Problem : timeout. Will retry in 4 seconds. 1 retries left.
##################################################################################################################### 100.0%##################################################################################################################### 100.0%
Checksum mismatch. 😔 Try again.

then if I retry again:

chronos@localhost / $ crew install torbrowser
torbrowser: 'The Onion Router' browser
https://www.torproject.org/
Version: 10.5.8
License: BSD, custom, MPL-2.0 and MIT
Performing pre-flight checks...
No precompiled binary available for your platform, downloading source...
##################################################################################################################### 100.0%##################################################################################################################### 100.0%
Checksum mismatch. 😔 Try again.

wtf , was so difficult to display that friggin message from the start instead BS my chromeos install with a heck of unnecessary pakages??

**Comment by satmandu** [comment]
Updated the hash. Try again?

`crew update ; crew install torbrowser`

**Comment by saltedcoffii** [comment]
> wtf , was so difficult to display that friggin message from the start instead BS my chromeos install with a heck of unnecessary pakages??
First off, please don't be rude to developers. It doesn't make us want to help you. We're a small team of volunteers who do this in our free time. Instead of being rude, be grateful that we're here to help despite your discourtesy. I would also like to reference this part of the DISCLAIMER OF WARRANTY clause in our license:

THE PROGRAM "AS IS" WITHOUT WARRANTY
OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF
ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

Onto your issue. It looks like @satmandu has updated the hash for the file, and is asking you to try again. If you find that it continues to fail, you may remove the “heck of unnecessary packages [sic]” by using the `crew autoremove` command. We look forward to getting this fixed for you and others that use the tor browser.

**Comment by Unixware** [comment]
should you first checking hashes etc before installing dependencies ? just saying...
-works thanks Sat
