### ISSUE TITLE
Issue with downloader not downloading

### ISSUE THREAD

**Issue by satmandu** [skycocker/chromebrew#6631]
![image](https://user-images.githubusercontent.com/1096701/149830508-1985b22a-02c3-4f11-9fd4-c13273ec2d20.png)

```
chronos@localhost /usr/local/lib/crew/packages (master %|SPARSE=)$ crew const | grep CURL
CURL=curl
```
This works though:
```
chronos@localhost /usr/local/lib/crew/packages (master %|SPARSE=)$ CURL=/usr/local/bin/curl crew install chrome
chrome: Google Chrome is a fast, easy to use, and secure web browser.
https://www.google.com/chrome
Version: 97.0.4692.71-1
License: google-chrome
Performing pre-flight checks...
No precompiled binary available for your platform, downloading source...
########################################################################################### 100.0%
Chrome archive downloaded.
```
Thoughts @supechicken ?

**Comment by satmandu** [comment]
The double slash in the url `https://dl.google.com/linux/chrome/deb//pool/main/g/google-chrome-stable/google-chrome-stable_97.0.4692.71-1_amd64.deb` causes the issue. This is a ruby bug, no?

**Comment by satmandu** [comment]
Maybe we need a bug filed upstream?

**Comment by supechicken** [comment]
Probably not an issue with slashes. Actually, I discovered this bug days ago, this is because the source url in `chrome.rb` will return a redirect message, the redirect url sent by `dl.google.com` looks like this:
```shell
/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_97.0.4692.71-1_amd64.deb
```
(Notice that it doesn't have a `https://` prefix nor domain name)

According to `lib/downloader.rb`, all urls without a `https://` or `file://` prefix will use `curl` instead of `net/http`. However, since the redirected url doesn't contain a domain name, `curl` will return an error then.

**Comment by supechicken** [comment]
I have added the some fixes in `https://github.com/supechicken666/chromebrew/tree/downloader_ftp`, it will complete the url if the protocol or domain name is missing

**Comment by satmandu** [comment]
> I have added some fixes in `https://github.com/supechicken666/chromebrew/tree/downloader_ftp`, it will complete the url if the protocol or domain name is missing

Did this make it into a PR?
