### ISSUE TITLE
Chrome Web App GUI

### ISSUE THREAD

**Issue by flyingP0tat0** [skycocker/chromebrew#673]
Does anyone know if it is possible ot create some sort of interaction of a web app and the shell / the internals? This way it would be possible to create a GUI which would invoke e.g. `crew install <package>` after the user selected a package.
Is something like this possible?

**Comment by finwo** [comment]
Based on how chrome apps are constructed, this should be possible. Each app (which runs in it's own window instead of just being a link to a web-page) is an v8 (node.js) background-process which is able to interact with the Chrome OS gui & internals through some API's provided by the OS.

Running command-line programs should be do-able form a chrome app.

Reading through the [Your first chrome app](https://developer.chrome.com/apps/first_app) documentation by google, you could even start the app from the terminal.

**Comment by flyingP0tat0** [comment]
Thank you for giving these resources. I think the best way to implement something like this would be building a service which would communicate with the GUI.
Thanks!
