### ISSUE TITLE
libsigsegv can't  be installed

### ISSUE THREAD

**Issue by jiacontrerasp** [skycocker/chromebrew#71]
Chromium OS by ArnoldTheBat
Versión 44.0.2365.0 (64-bit)
Plataforma 6963.0.2015_04_11_0624 (Developer Build - devbot-x64) developer-build amd64-generic

When I try run: sudo crew install libsigsegv 

Show me-->

Build Tools:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc -m64
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/libsigsegv-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
Preconfiguring package...
make: *** No rule to make target `check'.  Stop.
make: *** No rule to make target `install'.  Stop.
Installing...
Libsigsegv installed!

Anything else I can tell you?

**Comment by clshortfuse** [comment]
I did a couple of things I got it to installl.

I get this error when I try to do sudo ./compile

try without the sudo. you can also try running it from ~ or from /usr/local/tmp/crew

**Comment by alpinegizmo** [comment]
This is failing for me as well. The problem seems to be related to 64-bit vs 32-bit -- I'm running cloudready, and everything is 32-bit even though I have a 64-bit machine. configure decided to use -m64 and wants to find /usr/local/lib64, but that doesn't exist.

sudo or not, makes no difference.

chronos@localhost / $ cd ~
chronos@localhost ~ $ crew install libsigsegv
Found libsigsegv, version 2.10
Found libsigsegv, version 2.10
No precompiled binary available for your platform, downloading source...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2015-11-03 16:23:36--  ftp://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.10.tar.gz
           => 'libsigsegv-2.10.tar.gz'
Resolving ftp.gnu.org... 208.118.235.20
Connecting to ftp.gnu.org|208.118.235.20|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /gnu/libsigsegv ... done.
==> SIZE libsigsegv-2.10.tar.gz ... 402279
==> PASV ... done.    ==> RETR libsigsegv-2.10.tar.gz ... done.
Length: 402279 (393K) (unauthoritative)

libsigsegv-2.10.tar.gz             100%[==================================================================>] 392.85K   619KB/s   in 0.6s   

2015-11-03 16:23:42 (619 KB/s) - 'libsigsegv-2.10.tar.gz' saved [402279]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...

Build Tools:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc -m64
checking whether the C compiler works... no
configure: error: in `/usr/local/tmp/crew/libsigsegv-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
libsigsegv failed to install: `./configure --libdir=/usr/local/lib64/ CC="gcc -m64" CFLAGS=" -fPIC"` exited with 77

**Comment by ryanpcmcquen** [comment]
This fixes it:

https://github.com/skycocker/chromebrew/pull/114

**Comment by ryanpcmcquen** [comment]
Actually this makes the architecture value modular:

https://github.com/skycocker/chromebrew/pull/116
