### ISSUE TITLE
env: ruby: No such file or directory

### ISSUE THREAD

**Issue by guegrer** [skycocker/chromebrew#74]
i had an issue with my chromebook now when i run crew i got this error : env: ruby: No such file or directory

is there a way to reinstall crew ???

thanks in advance

**Comment by skycocker** [comment]
It would be best if you wiped out your whole `/usr/local` directory in such case, since your "issue" might have left some now wrongly addressed stuff. Are you using any other custom software on your chromebook besided chromebrew? If not, it would be easiest to just 
`sudo rm -r /usr/local/*` 
And then simply install chromebrew again. But if you're not certain if there's something else you might actually need from this directory, backup your `device.json` file, remove chromebrew, install it again and bring back the file (this might result in errors if there's some trash in your `/usr/local`):

`sudo mkdir /usr/local/crewbackup`
`sudo chown -R chronos:chronos /usr/local/crewbackup`
`cp /usr/local/etc/crew/device.json /usr/local/crewbackup`
`cp -r /usr/local/etc/crew/meta /usr/local/crewbackup`
`sudo rm -r /usr/local/etc/crew`
`sudo rm -r /usr/local/lib/crew`
`sudo rm -r /usr/local/tmp/crew`
`wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash`
`rm /usr/local/etc/crew/device.json`
`cp /usr/local/crewbackup/device.json /usr/local/etc/crew`
`rm -r /usr/local/etc/crew/meta`
`cp -r /usr/local/crewbackup/meta /usr/local/etc/crew` 

If these instructions result in errors/don't work/there's any other problem, you will have to wipe your `/usr/local` (after making a backup of data you need from there, if there are any of such) and install chromebrew again.

**Comment by guegrer** [comment]
thanks for your quick answer yes i have install castnow (nodejs) after my crew install about castnow there is ffmpeg feature that can transcode to mp4 is there will have a package fmpeg one day or impossible?


sorry for my poor english

**Comment by skycocker** [comment]
One day there will be, once someone decides to create one. Did you succeed in fixing your chromebrew? You can always wipe your `/usr/local`, reinstall chromebrew and then install back castnow.
