### ISSUE TITLE
LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by flyingP0tat0** [skycocker/chromebrew#896]
This is intended as a discussion about how to proceed on the problem with LD_LIBRARY_PATH.
It is a result from #873.

Any thoughts about a possible way to get around this problem?

**Comment by jam7** [comment]
There is previous discussion about possible ways to get around LD_LIBRARY_PATH problem is in #689.  If you want to general discussion, #689 is much better I think.  I suggest you to create your own issue since I thought you wanted to discuss whether modify user's environment or not to update LD_LIBRARY_PATH.

**Comment by flyingP0tat0** [comment]
Yes, that's right. Was not aware of that.
