### ISSUE TITLE
crew upgrade breaks ruby

### ISSUE THREAD

**Issue by jagalbraith** [skycocker/chromebrew#98]
Once you have installed chrome brew, run a crew update it works. Then crew upgrade and it fails and crew is broken at that point and needing to be re-installed. It throws an error that ruby cannot be found.

**Comment by thedamian** [comment]
Fixed in this issue: https://github.com/skycocker/chromebrew/issues/93

**Comment by thedamian** [comment]
To fix any issue with the "Checksum mismatch :/ try again" simply run

crew update

This will update all the /usr/local/lib/crew/packages/*.rb files and usually fixes any broken links (or broken checksum mismatches (which really are usually broken download links)

Still not working? Simply update your /usr/local/lib/crew/packages/ruby.rb with the contents on this page:
https://raw.githubusercontent.com/skycocker/chromebrew/master/packages/ruby.rb

**Comment by thedamian** [comment]
I think this issue should be closed.

**Comment by jparagon** [comment]
This is still breaking for me..

ruby could be updated from 2.0.0p247 to 2.0.0p247-chromeos1

Run 'crew upgrade' to upgrade everything or 'crew upgrade <packageName>' to upgrade a specific package.
chronos@localhost / $ crew upgrade
Updating packages...
Found ruby, version 2.0.0p247-chromeos1
Ruby removed!
Following packages also need to be installed: 
binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential readline zlibpkg 
Do you agree? [Y/n]

Proceeding...

[connection info]

ruby-2.0.0p247-chromeos-x86_64.tar 100%[==================================================================>]  26.98M  7.18MB/s   in 4.4s   

2016-01-05 08:08:11 (6.20 MB/s) - 'ruby-2.0.0p247-chromeos-x86_64.tar.gz' saved [28295655/28295655]

Checksum mismatch :/ try again
chronos@localhost / $ crew update
env: ruby: No such file or directory
chronos@localhost / $ ruby could be updated from 2.0.0p247 to 2.0.0p247-chromeos1
bash: ruby: command not found

**Comment by thedamian** [comment]
@jparagon help me out. My scroll up key on my mouse is broken. Can you scroll up two comments from yours to see the fix. 

thanks.

**Comment by jparagon** [comment]
Wow..   really?  Look I'm pointing out that by using the default suggestion to upgrade it is breaking things, even after crew update, not so much that there isn't a "fix".

**Comment by Kriskras99** [comment]
@jparagon here's a temporary fix:
```shell
cd ~/Downloads
wget https://www.dropbox.com/s/x3jt0z5i1r4afyv/ruby-2.0.0p247-chromeos-x86_64.tar.gz?dl=1 -O ruby-2.0.0p247-chromeos-x86_64.tar.gz
tar -xf ruby-2.0.0p247-chromeos-x86_64.tar.gz
sudo cp -r ./usr/* /usr
wget https://github.com/skycocker/chromebrew/blob/master/packages/ruby.rb
cp ruby.rb /usr/local/lib/crew/packages/ruby.rb
rm -rf usr/ ruby.rb ruby-2.0.0p247-chromeos-x86_64.tar.gz # this is optional but will remove the downloaded files
crew update
sudo crew upgrade
```

**Comment by jagalbraith** [comment]
Updating the ruby.rb file seemed to do the trick for my system. Thank you. Did these comments get a little snippy or am I reading in to things?

**Comment by jparagon** [comment]
Thanks,  I probably wasn't clear. I know there is a fix.. I was responding to this

"To fix any issue with the "Checksum mismatch :/ try again" simply run

crew update

Still not working? ""

I was assuming at this point there was a thought that this may be fixed without having to manually update the file.  So I was attempting to help with feedback, not with a problem to solve. Sorry for anyone's mouse scroll that may be broken ¯\_(ツ)_/¯

**Comment by jagalbraith** [comment]
My point is that if there is a problem, lets work together and solve it in the most professional matter.

**Comment by thedamian** [comment]
It's "Update" not "upgrade"

If you do a "crew update" then the package files get updated.
You still need to do a "crew upgrade ruby" (for example) AFTER the "crew update"

HAVING SAID THAT... I completely understand the confusion @jparagon I looked at your post a couple of times and was scratching my head and thinking that SHOULD have worked!

I think we should think of different names other than "upgrade" and "update" which sound EXACTLY the same.

Maybe something more specific  like "crew updatelist" or "crew updatepackages" so that there's less confusion as to whether you're upgrading to the latest version of the software you want. or if you're getting the newest list of formulas (or package lists) for crew to take care of.

@jparagon  please let us know if this worked. Thanks.

**Comment by jagalbraith** [comment]
I agree. The terminology, though by nature follows aptitude / apt-get, is confusing. Something simple like crew getpackages and crew upgrade would set them apart.

**Comment by jparagon** [comment]
@thedamian cool thanks for the info. So I did install -> update -> upgrade -> (checksum mismatch) -> update or upgrade (result in env: ruby: No such file or directory)

Seems like the removal of Ruby followed by the checksum mismatch leaves crew in an inoperable state, which I guess makes sense since Ruby is removed and then the installer has forcibly quit. 

chronos@localhost / $ crew upgrade
Updating packages...
Found ruby, version 2.0.0p247-chromeos1
Ruby removed!
-> checksum error

**Comment by jparagon** [comment]
Personally I don't have a problem with the terminology. Update vs upgrade is pretty standard (unless I'm totally missing something here).

Vanilla install 
986937249 539 /usr/local/lib/crew/packages/ruby.rb
after crew update
986937249 539 /usr/local/lib/crew/packages/ruby.rb
updated file is
1071586258 31261 ruby.rb

**Comment by skycocker** [comment]
can we consider it fixed now or is there anything more we could do for the people with broken ruby?

**Comment by jparagon** [comment]
I looked into this a little more today just trying to understand what is happening and to me it seems that the original ruby.rb file is served and the update never updates the file. As show above the checksum after the update is the same. Is this only a subset of people that this is happening to? If you were to install > update ruby.rm > upgrade does everything work okay?

**Comment by jparagon** [comment]
Okay so I do see a bit of the update / upgrade confusion now. For me it was this message: 
$ crew upgrade
Updating packages...  

Then looking at the code (sorry, finally got a chance) I can see where it is intermingled. e.g. 
```
+ " could be updated from " + package[:version] + " to " + @pkg.version
```

```
upgrade <packageName>' to upgrade a specific package
```
I'll submit a suggestion for this if I come up with a thought.

But I am still curious, why does the upgrade not work if it is using the file that @thedamian checked in to Master?

**Comment by thedamian** [comment]
@jparagon  

Please type:
crew update
crew upgrade ruby

And see if that works.

(please copy and paste what you see above because I think you're getting confused.

**Comment by jparagon** [comment]
@thedamian that is the exact workflow I've been doing, does that work for everyone else? Here is the full output:

```
chronos@localhost ~/source/chromebrew $ crew update
From https://github.com/skycocker/chromebrew
 * branch            master     -> FETCH_HEAD
HEAD is now at 906f6bf Merge pull request #129 from Tivoli/tivs/add-redis
Package lists, crew, and library updated.
Checking for package updates...

ruby could be updated from 2.0.0p247 to 2.0.0p247-chromeos1

Run 'crew upgrade' to upgrade everything or 'crew upgrade <packageName>' to upgrade a specific package.
chronos@localhost ~/source/chromebrew $ crew upgrade ruby
Found ruby, version 2.0.0p247-chromeos1
Found ruby, version 2.0.0p247-chromeos1
Updating ruby...
Ruby removed!
Following packages also need to be installed: 
binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential readline zlibpkg 
Do you agree? [Y/n]

Proceeding...
Found binutils, version 2.23.2
Package binutils already installed, skipping...
Found gmp, version 5.1.2
Package gmp already installed, skipping...
Found mpc, version 1.0.1
Package mpc already installed, skipping...
Found mpfr, version 3.1.2
Package mpfr already installed, skipping...
Found glibc, version 2.17.90-baseline
Package glibc already installed, skipping...
Found gcc, version 4.8.1-baseline
Package gcc already installed, skipping...
Found make, version 3.82
Package make already installed, skipping...
Found linuxheaders, version 3.4.0
Package linuxheaders already installed, skipping...
Found buildessential, version 1.0
Package buildessential already installed, skipping...
Found readline, version 6.2
Package readline already installed, skipping...
Found zlibpkg, version 1.2.8
Package zlibpkg already installed, skipping...
Found ruby, version 2.0.0p247-chromeos1
Precompiled binary available, downloading...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2016-01-06 16:24:46--  https://www.dropbox.com/s/x3jt0z5i1r4afyv/ruby-2.0.0p247-chromeos-x86_64.tar.gz?dl=1
Resolving www.dropbox.com... 108.160.172.238, 108.160.172.206
Connecting to www.dropbox.com|108.160.172.238|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://dl.dropboxusercontent.com/content_link/hvL7VUsYiOI618oznD7aQQnMK0uQj0mRJxgbsJvsJNv1y8HipCbQFK0HpHFfbLmr/file?dl=1 [following]
--2016-01-06 16:24:47--  https://dl.dropboxusercontent.com/content_link/hvL7VUsYiOI618oznD7aQQnMK0uQj0mRJxgbsJvsJNv1y8HipCbQFK0HpHFfbLmr/file?dl=1
Resolving dl.dropboxusercontent.com... 45.58.74.5, 45.58.74.37
Connecting to dl.dropboxusercontent.com|45.58.74.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 28295655 (27M) [application/octet-stream]
--2016-01-06 16:24:48--  https://dl.dropboxusercontent.com/content_link/hvL7VUsYiOI618oznD7aQQnMK0uQj0mRJxgbsJvsJNv1y8HipCbQFK0HpHFfbLmr/file?dl=1
Reusing existing connection to dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 28295655 (27M) [application/octet-stream]
Saving to: 'ruby-2.0.0p247-chromeos-x86_64.tar.gz'

ruby-2.0.0p247-chromeos-x86_64.tar 100%[==================================================================>]  26.98M  7.97MB/s   in 3.8s   

2016-01-06 16:24:53 (7.03 MB/s) - 'ruby-2.0.0p247-chromeos-x86_64.tar.gz' saved [28295655/28295655]

Checksum mismatch :/ try again
chronos@localhost ~/source/chromebrew $ crew
env: ruby: No such file or directory
chronos@localhost ~/source/chromebrew $ 

```

**Comment by thedamian** [comment]
You are indeed doing everything right @jparagon

To test I screwed up ruby and crew (thanks to @Kriskras99  I'm back)

I did the following 

crew remove ruby    <~-- Be careful. This screws up crew
(then followed @Kriskras99 to get it back)

But Luckily it was an older version of ruby.
So I could successfully do "crew upgrade ruby" with complete success.

Here's my output:

chronos@localhost ~/Downloads/tmp $ crew upgrade ruby
Found ruby, version 2.2.4
Found ruby, version 2.2.4
Updating ruby...
Package ruby isn't installed.
Following packages also need to be installed: 
binutils gmp mpc mpfr glibc gcc make linuxheaders buildessential readline zlibpkg 
Do you agree? [Y/n]
Y
Proceeding...
Found binutils, version 2.23.2
Package binutils already installed, skipping...
Found gmp, version 5.1.2
Package gmp already installed, skipping...
Found mpc, version 1.0.1
Package mpc already installed, skipping...
Found mpfr, version 3.1.2
Package mpfr already installed, skipping...
Found glibc, version 2.17.90-baseline
Package glibc already installed, skipping...
Found gcc, version 4.8.1-baseline
Package gcc already installed, skipping...
Found make, version 3.82
Package make already installed, skipping...
Found linuxheaders, version 3.4.0
Package linuxheaders already installed, skipping...
Found buildessential, version 1.0
Package buildessential already installed, skipping...
Found readline, version 6.2
Package readline already installed, skipping...
Found zlibpkg, version 1.2.8
Package zlibpkg already installed, skipping...
Found ruby, version 2.2.4
No precompiled binary available for your platform, downloading source...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2016-01-07 10:35:01--  https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.4.tar.gz
Resolving cache.ruby-lang.org... 199.27.76.233
Connecting to cache.ruby-lang.org|199.27.76.233|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16638151 (16M) [application/octet-stream]
--2016-01-07 10:35:06--  https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.4.tar.gz
Reusing existing connection to cache.ruby-lang.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 16638151 (16M) [application/octet-stream]
Saving to: 'ruby-2.2.4.tar.gz'

ruby-2.2.4.tar.gz                  100%[=================================================================>]  15.87M  2.18MB/s   in 6.5s   

2016-01-07 10:35:13 (2.43 MB/s) - 'ruby-2.2.4.tar.gz' saved [16638151/16638151]

Archive downloaded
Unpacking archive, this may take a while...
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
config.guess already exists
.... A BUNCH of lines of course irrelevant because it's already passed the checksum here ---
installing rdoc:              /usr/local/share/ri/2.2.0/system
installing capi-docs:         /usr/local/share/doc/ruby
Installing...
Ruby installed!


SO...

So you've proven that "crew update" works (since the file you're trying to download IS the latest ruby.rb file) 
AND by mistake (or on purpose ;) I was able to test what you're having problems and it worked for me.

NOW....

1) I can see you're following the correct steps. 
2) I can see you're installing it on a x64 machine (NICE!) so am I
3) I can see that you've downloaded the correct file and get the same download bits I do (So it's no an issue with the file missing like it is with others
4) I THINK the problem is the checksum (Which has worked on my box)

So I can guess only one thing. DATE.

Check your date. the checksum and downloads rely on you having a correct date. 

BUT To a new point.

CAN WE CLOSE THIS ISSUE?

1) We've tested and proved that crew update works.
2) I've tested (inadvertently) that "crew upgrade ruby" works on a x64 machine (what you seem to have)
3) We have a fix for the issue on YOUR box (the line  from @Kriskras99 post that saved my butt) https://github.com/skycocker/chromebrew/issues/98#issuecomment-169059266

So What do you think? Can we close this issue?

**Comment by thedamian** [comment]
OH CRAP! I have an updated ruby.rb file from @Tivoli https://github.com/skycocker/chromebrew/pull/124/files

Maybe that's why that worked so well. Damn!

Hmmm...Having said that I'm going back to what else I thought might be the issue. I'm getting a different sha signature for that ruby file in the current ruby.rb

@jparagon can you update manually your /usr/local/lib/crew/packages/ruby.rb and the sha1 signature to this one: 

f1de1ef5ed690c3b78f4e40208a4fb93e227c4ed  

then run it again, and if that works I'll put in a pull request.

**Comment by thedamian** [comment]
@jparagon 

I've made a pull request with this fix:
https://github.com/skycocker/chromebrew/pull/134

Please copy the contents of this file: 
/usr/local/lib/crew/packages/ruby.rb  with this: https://raw.githubusercontent.com/thedamian/chromebrew/master/packages/ruby.rb

If this fixes the issue please let us know and more importantly close this issue AND PLEASE comment on the pull.

thank you

**Comment by thedamian** [comment]
@jparagon you're life just because very easy thanks to our amazing leader @skycocker 

He's just merged https://github.com/skycocker/chromebrew/pull/134

Now just do

crew update
crew upgrade ruby

Or even better yet.

crew update
crew install ruby_latest

Newest version of ruby for you.

**Comment by jparagon** [comment]
"@jparagon you're life just because very easy thanks to our amazing leader @skycocker"
@thedamian  What? LOL

So I had some time to test (holy crap!) before getting to my email and seeing these updates. But just to confirm I went down the same path and added some debug
```
checksum file ruby-2.0.0p247-chromeos-x86_64.tar.gz is f1de1ef5ed690c3b78f4e40208a4fb93e227c4ed
checksum expect ec4d9c9d1a993ca03d0dee594c79ab1945e5b88d
Checksum mismatch :/ try again
```
Confirms my confusion as to why this would only break for a subset of users, anyone could try and break right? 

Just to be clear I actually did not need this, I'm just trying to help out with something that was seemingly broken for other users. I'm thinking I'll be spending some time in this space so feel free not to play the support role with me. I'll due diligence to debug / pull request / etc..  I think this is a great effort. 

That being said, I'll comment on the PR for this and submit a new PR with some changes to help avoid this in the future & some suggestions for the upgrade / update terminology. 

thx @thedamian @skycocker (our hero!) close away..

**Comment by thedamian** [comment]
@jparagon and @jagalbraith 

can you do a 
crew update 
crew upgrade ruby

one more time. We have a fix that's already on.

If this fixes it for both of you please @jagalbraith close the ticket.

thanks @jparagon for your input in this.

**Comment by jagalbraith** [comment]
@jparagon  You are dead on with it only breaks for a subset of users. It continues to break for parallels version of chromeOS but on the Chromebook sitting next to me it works. I am chalking this up as a Parallels problem and closing the ticket. Thank you for all your effort guys. My temp fix for this is to build a ruby repair script in bash in the case that I do a crew upgrade. 

Again, thanks fellas.
